export interface BlogPost {
  id: string;
  slug: string;
  title: string;
  subtitle: string;
  category: string;
  readTime: string;
  date: string;
  image: string;
  imageAlt: string;
  excerpt: string;
  content: BlogSection[];
}

export interface BlogSection {
  type: "paragraph" | "heading" | "subheading" | "list" | "callout" | "tip";
  text?: string;
  items?: string[];
}

// Unsplash images — trade/contractor themed
const IMGS = {
  phone: "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=1200&q=80",
  google: "https://images.unsplash.com/photo-1573804633927-bfcbcd909acd?w=1200&q=80",
  reviews: "https://images.unsplash.com/photo-1600880292203-757bb62b4baf?w=1200&q=80",
  plumber: "https://images.unsplash.com/photo-1607472586893-edb57bdc0e39?w=1200&q=80",
  roofing: "https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=1200&q=80",
  hvac: "https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=1200&q=80",
  social: "https://images.unsplash.com/photo-1611162617213-7d7a39e9b1d7?w=1200&q=80",
  website: "https://images.unsplash.com/photo-1467232004584-a241de8bcf5d?w=1200&q=80",
  leads: "https://images.unsplash.com/photo-1553877522-43269d4ea984?w=1200&q=80",
  ai: "https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=1200&q=80",
  mindset: "https://d2xsxph8kpxj0f.cloudfront.net/310519663485111386/EofNE7tr7Zd2Ma3kz46p6x/blog-hero-ai-mindset-6AHwRRjXKpPWGKJWLpj68P.webp",
};

export const blogPosts: BlogPost[] = [
  {
    id: "1",
    slug: "why-you-lose-leads-before-you-even-know-you-had-them",
    title: "Por Qué Pierdes Leads Antes de Saber Que Los Tenías",
    subtitle: "La razón #1 por la que los contractors pierden jobs — y no tiene nada que ver con tu precio.",
    category: "Lead Generation",
    readTime: "5 min read",
    date: "March 20, 2026",
    image: IMGS.phone,
    imageAlt: "Contractor revisando el teléfono por llamadas perdidas",
    excerpt: "La mayoría de los contractors piensan que pierden jobs por el precio. La verdadera razón es el tiempo de respuesta. Aquí te contamos qué dice la data — y qué puedes hacer hoy mismo.",
    content: [
      { type: "paragraph", text: "Aquí tienes un escenario que pasa cientos de veces al día para contractors en todo el país: Un homeowner necesita arreglar su HVAC. Busca en Google, encuentra tres contractors, y les manda mensaje a los tres. El primero que responde se lleva el job. Los otros dos nunca reciben respuesta." },
      { type: "paragraph", text: "Esto no es un guess. Es lo que muestra la data. El 78% de los leads van al primer negocio que responde. Y el contractor promedio tarda más de 2 horas en responder una nueva consulta — si es que responde." },
      { type: "heading", text: "El Verdadero Problema No Es Tu Precio" },
      { type: "paragraph", text: "Cuando los contractors pierden jobs, usualmente culpan al precio. 'El cliente se fue con alguien más barato.' Pero en la mayoría de los casos, el cliente eligió al que le devolvió la llamada primero. Ni siquiera se habló de precio." },
      { type: "paragraph", text: "Piénsalo desde el lado del cliente. Tiene una tubería rota. Está estresado. Manda tres mensajes. Un contractor le responde en 10 minutos. Los otros dos al día siguiente. ¿A quién crees que contrata?" },
      { type: "callout", text: "\"El 78% de los clientes contratan al primer contractor que responde. El tiempo promedio de respuesta para contractors es más de 2 horas.\"" },
      { type: "heading", text: "Por Qué Es Tan Difícil Responder Rápido para los Contractors" },
      { type: "paragraph", text: "No estás sentado en un escritorio esperando consultas. Estás en un techo. Estás bajo un fregadero. Estás manejando entre jobs. Responder cada llamada y mensaje en el momento que llega es físicamente imposible cuando estás haciendo el trabajo real." },
      { type: "paragraph", text: "Este es el problema fundamental de manejar un negocio de trade — las mismas habilidades que te hacen excelente en tu oficio hacen difícil manejar el lado del negocio. No puedes estar en dos lugares al mismo tiempo." },
      { type: "heading", text: "Qué Puedes Hacer Al Respecto" },
      { type: "paragraph", text: "La buena noticia es que este problema tiene solución — y no necesitas contratar recepcionista ni estar pegado al teléfono para arreglarlo." },
      { type: "list", items: [
        "Configura una respuesta automática por texto que se envíe justo cuando alguien llena tu formulario de contacto — aunque sea solo 'Recibimos tu mensaje, te llamamos en la hora.'",
        "Usa un sistema de texto automático para llamadas perdidas, así quien te llame y no te encuentre recibe un texto instantáneo.",
        "Considera un AI agent que pueda contestar llamadas y mensajes 24/7, calificar leads, y agendar estimados en tu calendario.",
        "Al menos, revisa tus mensajes cada 2 horas y responde el mismo día hábil.",
      ]},
      { type: "tip", text: "Pro Tip: Incluso un texto automático simple que diga 'Gracias por contactarnos! Te llamamos en la hora' puede aumentar mucho tu tasa de cierre. Muestra al cliente que eres responsive y profesional — y te da tiempo para terminar el job que tienes." },
      { type: "heading", text: "La Conclusión" },
      { type: "paragraph", text: "Probablemente haces un gran trabajo. Tus clientes te quieren. Pero si no respondes rápido a nuevas consultas, estás dejando dinero sobre la mesa todos los días. Arregla tu tiempo de respuesta y verás cómo sube tu tasa de cierre — sin cambiar nada más en tu negocio." },
    ],
  },
  {
    id: "2",
    slug: "how-to-get-more-google-reviews-without-begging",
    title: "Cómo Conseguir Más Reviews en Google Sin Tener Que Rogar",
    subtitle: "Un sistema simple que te consigue un flujo constante de reviews 5 estrellas — en automático.",
    category: "Google & Reviews",
    readTime: "6 min read",
    date: "March 15, 2026",
    image: IMGS.reviews,
    imageAlt: "Review de cinco estrellas en pantalla de teléfono",
    excerpt: "Las reviews en Google son el factor #1 para ranking local. Aquí tienes un sistema simple y repetible para conseguir más sin conversaciones incómodas con clientes.",
    content: [
      { type: "paragraph", text: "Si quieres más jobs desde Google, necesitas más reviews. Así de simple. El algoritmo de Google mira la cantidad de reviews, la calidad, y qué tan recientes son. Un contractor con 80 reviews casi siempre supera a uno con 8 — aunque el de 8 haga mejor trabajo." },
      { type: "paragraph", text: "El problema que tienen la mayoría de contractors no es que sus clientes no quieran dejar reviews. Es que nunca piden — o lo hacen de una forma que se siente incómoda y complicada." },
      { type: "heading", text: "Por Qué Los Clientes No Dejan Reviews (Aunque Te Amen)" },
      { type: "paragraph", text: "Tus clientes están ocupados. Tuvieron una buena experiencia, querían dejar review, y luego la vida se interpuso. No es que no quieran — es que requiere esfuerzo, y el esfuerzo necesita una razón." },
      { type: "paragraph", text: "La solución es hacerlo lo más fácil posible y pedir en el momento justo." },
      { type: "callout", text: "\"El 88% de consumidores confían en reviews online tanto como en recomendaciones personales. Contractors con 50+ reviews reciben 3x más llamadas que los que tienen menos de 10.\"" },
      { type: "heading", text: "El Momento Correcto para Pedir" },
      { type: "paragraph", text: "El mejor momento para pedir un review es justo después de terminar un job — cuando el cliente está más feliz. Es cuando acaban de ver tu trabajo, están aliviados que el problema se resolvió, y se sienten bien con el dinero que gastaron." },
      { type: "paragraph", text: "No esperes una semana. No mandes email tres días después. Pide en ese momento, en persona o por texto dentro de la hora de terminar el job." },
      { type: "heading", text: "El Script Simple Que Funciona" },
      { type: "paragraph", text: "En persona, al final del job, di esto: 'Oye [nombre], me alegra que pudimos ayudarte. Si tienes 60 segundos, un review en Google nos ayudaría un montón — ayuda a otros homeowners a encontrarnos. Te mando el link por texto ahora mismo.'" },
      { type: "paragraph", text: "Luego saca tu teléfono y mándales el link directo a tu página de reviews en Google. Listo." },
      { type: "list", items: [
        "Crea un link corto a tu página de reviews en Google (búscalo en Google — toma 2 minutos configurarlo).",
        "Guárdalo en tu teléfono como plantilla de texto para enviarlo con un tap.",
        "Mándalo dentro de los 30 minutos después de terminar el job mientras la experiencia está fresca.",
        "Haz un follow-up una vez, 48 horas después, si no han dejado review aún.",
      ]},
      { type: "tip", text: "Pro Tip: Nunca pidas un 'review de 5 estrellas.' Solo pide un 'review honesto.' Esto se siente menos forzado y en realidad resulta en más reviews — y casi siempre son 5 estrellas si hiciste buen trabajo." },
      { type: "heading", text: "Automatízalo Para Que Nunca Se Te Olvide" },
      { type: "paragraph", text: "Los mejores contractors no dependen de recordar pedir. Tienen un sistema que manda automáticamente un texto pidiendo review después de cada job terminado. Así, todos los clientes reciben la petición — no solo los que recuerdas." },
      { type: "paragraph", text: "Con un sistema así, un contractor que hace 5 jobs a la semana podría sumar 100+ reviews nuevas al año. Esa es la diferencia entre estar en la página 3 y estar en los top 3 en Google." },
    ],
  },
  {
    id: "3",
    slug: "the-truth-about-contractor-websites-that-nobody-tells-you",
    title: "La Verdad Sobre Las Websites de Contractors Que Nadie Te Cuenta",
    subtitle: "La mayoría de las websites de contractors te están costando jobs. Aquí te decimos por qué — y cómo es una buena website realmente.",
    category: "Website & SEO",
    readTime: "7 min read",
    date: "March 10, 2026",
    image: IMGS.website,
    imageAlt: "Website de contractor en pantalla de laptop",
    excerpt: "Tener una website no es suficiente. Una mala website puede hacerte más daño que no tener ninguna. Aquí te contamos qué separa una website que genera leads de una que no.",
    content: [
      { type: "paragraph", text: "La mayoría de los contractors tienen website. Muy pocos tienen una website que realmente funciona. Hay una gran diferencia entre tener website y tener una que trae leads, genera confianza, y convierte visitantes en clientes que pagan." },
      { type: "paragraph", text: "La dura verdad es que una mala website puede hacerte daño. Si un cliente potencial visita tu sitio y se ve viejo, carga lento, o no funciona en su teléfono — se va. Y probablemente va con tu competencia." },
      { type: "heading", text: "Qué Hacen Los Clientes Antes de Llamarte" },
      { type: "paragraph", text: "El 75% de la gente juzga la credibilidad de un negocio por su website. Antes de llamar, están viendo tu sitio, leyendo tus reviews, y comparándote con la competencia. Tienes como 0.05 segundos para dar una buena primera impresión." },
      { type: "callout", text: "\"El 75% de consumidores juzgan la credibilidad de una empresa por el diseño de su website. Tienes 0.05 segundos para dar una primera impresión.\""},
      { type: "heading", text: "Las 5 Cosas Que Una Website de Contractor Debe Tener" },
      { type: "list", items: [
        "Un headline claro que diga exactamente qué haces y dónde — 'Reparación e instalación HVAC en Phoenix, AZ' no solo 'Bienvenidos a Nuestra Website.'",
        "Fotos reales de tu trabajo — no fotos genéricas. Los clientes quieren ver lo que hiciste, no una imagen de una llave inglesa.",
        "Tu número de teléfono visible en la parte superior de cada página, lo suficientemente grande para tocar en el teléfono.",
        "Reviews y testimonios de clientes reales — idealmente sacados directamente de Google.",
        "Un formulario de contacto simple o botón de reserva que funcione en móvil.",
      ]},
      { type: "heading", text: "Por Qué El Móvil Importa Más De Lo Que Crees" },
      { type: "paragraph", text: "Más del 60% de las búsquedas de contractors locales se hacen en teléfono. Si tu website no se ve bien y funciona perfecto en móvil, estás perdiendo más de la mitad de tus clientes potenciales antes de que lean una palabra." },
      { type: "paragraph", text: "Prueba tu propia website ahora mismo. Ábrela en tu teléfono. ¿Carga rápido? ¿El texto se lee sin hacer zoom? ¿Puedes tocar el número para llamar? Si alguna respuesta es no, tienes un problema." },
      { type: "heading", text: "El Factor SEO" },
      { type: "paragraph", text: "Tu website también tiene que ser fácil de encontrar. Eso significa optimizarla para búsqueda local — las palabras clave correctas, la estructura correcta, y actualizaciones regulares. Una website que nunca cambia es una website que Google deja de tomar en cuenta." },
      { type: "tip", text: "Pro Tip: Agrega una página nueva o un blog post a tu website al menos una vez al mes. No tiene que ser largo — hasta 300 palabras sobre un proyecto reciente o una pregunta común de clientes le dice a Google que tu sitio está activo y relevante." },
      { type: "heading", text: "La Conclusión" },
      { type: "paragraph", text: "Tu website es tu activo de marketing más importante. Trabaja 24/7, es lo primero que ven los clientes, y genera confianza o la destruye. Invertir en una buena website no es un lujo — es la base de todo lo demás que haces en marketing." },
    ],
  },
  {
    id: "4",
    slug: "how-to-use-social-media-as-a-contractor-without-wasting-time",
    title: "Cómo Usar Social Media Como Contractor Sin Perder Horas",
    subtitle: "No necesitas ser influencer. Solo necesitas un sistema simple que funcione.",
    category: "Social Media",
    readTime: "6 min read",
    date: "March 5, 2026",
    image: IMGS.social,
    imageAlt: "Contractor publicando fotos de jobs en social media",
    excerpt: "La mayoría de contractors o ignoran social media o le dedican demasiado tiempo sin resultados. Aquí tienes el enfoque simple y de bajo esfuerzo que realmente trae jobs.",
    content: [
      { type: "paragraph", text: "Cuando los contractors piensan en social media, usualmente tienen una de dos reacciones: 'No tengo tiempo para eso' o 'Lo intenté y no funcionó.' Ambas tienen sentido — porque la mayoría de consejos de social media están diseñados para influencers, no para alguien que pasa el día arreglando techos." },
      { type: "paragraph", text: "La verdad es: no necesitas postear todos los días. No necesitas bailar en TikTok. No necesitas estrategia de contenido ni voz de marca. Solo necesitas mostrar tu trabajo consistentemente y dejar que la calidad hable por sí sola." },
      { type: "heading", text: "Por Qué Social Media Realmente Importa Para Contractors" },
      { type: "paragraph", text: "Antes de contratar un contractor, la mayoría de los homeowners hacen investigación. Revisan reviews en Google, ven tu website, y — cada vez más — revisan tu social media. No para ver si eres entretenido, sino para ver si eres real, si haces buen trabajo, y si otros han tenido buenas experiencias contigo." },
      { type: "callout", text: "\"El 93% de homeowners revisan presencia online antes de contratar un contractor. Social media ahora es parte de ese proceso.\""},
      { type: "heading", text: "El Sistema Simple Que Funciona" },
      { type: "paragraph", text: "La única estrategia de social media que necesitas como contractor es esta: postea fotos de tu trabajo, antes y después cuando puedas, con una descripción corta de qué hiciste y dónde. Eso es todo." },
      { type: "list", items: [
        "Toma 3-5 fotos en cada job — antes de empezar, durante, y después.",
        "Postea una foto por job en Instagram y Facebook con un caption de 2-3 oraciones.",
        "Incluye tu ciudad y servicio en el caption para beneficio de SEO local.",
        "Responde a cada comentario, aunque sea con un pulgar arriba.",
        "Postea consistentemente — 2-3 veces por semana es mejor que 10 veces una semana y nada por un mes.",
      ]},
      { type: "heading", text: "Qué Postear Cuando No Tienes Fotos Nuevas" },
      { type: "paragraph", text: "Algunas semanas son lentas. Algunos jobs no son fotogénicos. Aquí qué postear cuando no tienes contenido fresco:" },
      { type: "list", items: [
        "Un tip o consejo para homeowners (ejemplo: 'Cambia el filtro de tu HVAC cada 3 meses para evitar reparaciones caras')",
        "Un antes y después de un job anterior",
        "Un testimonio o review de cliente",
        "Una foto de tu truck o equipo en un job site",
        "Una pregunta para tus seguidores ('¿Cuál es el problema de plomería más común en tu área?')",
      ]},
      { type: "tip", text: "Pro Tip: La forma más fácil de mantener consistencia en social media es batch your content. Al final de cada semana, dedica 20 minutos a escribir captions para todas las fotos que tomaste esa semana y programa que se publiquen automáticamente. Herramientas como Buffer o Later hacen esto simple." },
      { type: "heading", text: "La Conclusión" },
      { type: "paragraph", text: "Social media para contractors no es para volverse viral. Es para ser visible, lucir profesional, y construir un historial de trabajos terminados que los clientes potenciales puedan ver. Un enfoque simple y consistente gana a una estrategia elaborada que nunca sigues." },
    ],
  },
  {
    id: "5",
    slug: "what-is-ai-marketing-and-why-every-contractor-needs-it-in-2026",
    title: "Qué Es AI Marketing — Y Por Qué Todo Contractor Lo Necesita en 2026",
    subtitle: "El AI no es solo para empresas tech. Aquí cómo está cambiando el juego para negocios locales de trade.",
    category: "AI Marketing",
    readTime: "7 min read",
    date: "February 28, 2026",
    image: IMGS.ai,
    imageAlt: "Concepto de tecnología AI para marketing de pequeños negocios",
    excerpt: "Has oído hablar del AI. Pero, ¿qué significa realmente para tu negocio de plumbing, HVAC, o roofing? Aquí una explicación sencilla de qué es AI marketing y por qué te importa.",
    content: [
      { type: "paragraph", text: "Cada semana hay un nuevo headline sobre AI. Puede ser abrumador — especialmente cuando manejas un negocio de trade y solo quieres enfocarte en hacer buen trabajo. Pero la verdad es: el AI ya está cambiando cómo los clientes encuentran y contratan contractors, y si no prestas atención, tus competidores te van a sacar ventaja." },
      { type: "paragraph", text: "La buena noticia es que no necesitas entender cómo funciona el AI para beneficiarte. Solo necesitas saber qué puede hacer por tu negocio." },
      { type: "heading", text: "Qué Significa Realmente AI Marketing" },
      { type: "paragraph", text: "AI marketing significa usar software que puede pensar, aprender, y actuar — sin que tengas que decirle qué hacer cada vez. En vez de que tú sigas cada lead manualmente, respondas cada review, o postees en social media, el AI lo hace automáticamente." },
      { type: "paragraph", text: "Piénsalo como tener un equipo completo de marketing trabajando para ti 24/7 — que nunca duerme, nunca olvida, y nunca tiene un mal día." },
      { type: "callout", text: "\"Contractors que usan herramientas de AI marketing ven en promedio 3x más leads y 40% más ingresos en los primeros 6 meses.\""},
      { type: "heading", text: "Las 5 Formas en Que El AI Ya Está Ayudando a Contractors" },
      { type: "list", items: [
        "Contestar llamadas y mensajes instantáneamente, 24/7 — incluso cuando estás en un job site",
        "Hacer follow-up automático con leads para que ninguno se pierda",
        "Generar y responder reviews en Google sin que muevas un dedo",
        "Postear tu trabajo en social media consistentemente, cada semana",
        "Mantener a clientes pasados comprometidos con ofertas y recordatorios estacionales",
      ]},
      { type: "heading", text: "¿Es Complicado Configurarlo?" },
      { type: "paragraph", text: "Esta es la pregunta que más escuchamos. Y la respuesta honesta es: depende de quién lo configure. Si intentas juntar diferentes herramientas tú mismo, sí — puede ser complicado y tomar mucho tiempo." },
      { type: "paragraph", text: "Pero si trabajas con una empresa que se especializa en AI marketing para contractors, ellos manejan toda la configuración técnica. Tú solo llegas y haces el trabajo que te gusta. El AI se encarga del resto." },
      { type: "tip", text: "Pro Tip: No necesitas entender AI para usarlo. No entiendes cómo funciona el motor de tu truck, pero igual lo manejas a cada job. Las herramientas de AI marketing son igual — solo necesitas saber qué hacen, no cómo lo hacen." },
      { type: "heading", text: "Los Contractors Que Ganarán en 2026" },
      { type: "paragraph", text: "Los contractors que prosperen en los próximos años no serán necesariamente los más hábiles o los más baratos. Serán los que respondan más rápido, se vean más profesionales online, y tengan sistemas que funcionen incluso cuando estén ocupados." },
      { type: "paragraph", text: "AI marketing es cómo construyes esos sistemas sin contratar un equipo completo de marketing. Y mientras antes empieces, más ventaja tendrás sobre competidores que aún hacen todo manual." },
    ],
  },
  {
    id: "6",
    slug: "how-to-get-your-plumbing-business-to-show-up-on-google",
    title: "Cómo Hacer Que Tu Negocio de Trade Aparezca en Google",
    subtitle: "Una guía sencilla de SEO local para contractors que no son tech-savvy.",
    category: "Google & Reviews",
    readTime: "8 min read",
    date: "February 22, 2026",
    image: IMGS.google,
    imageAlt: "Resultados de búsqueda en Google en laptop para contractor local",
    excerpt: "Aparecer en Google cuando alguien busca tu servicio en tu área es el marketing más valioso que puedes hacer. Aquí te explicamos exactamente cómo funciona y qué tienes que hacer.",
    content: [
      { type: "paragraph", text: "Cuando alguien en tu área busca 'reparación HVAC cerca de mí' o 'plomero de emergencia [tu ciudad],' Google les muestra una lista de negocios locales. Los que están arriba reciben la mayoría de las llamadas. Los que están en la página 2 casi ninguna." },
      { type: "paragraph", text: "Hacer que tu negocio aparezca en esos resultados top se llama SEO local (Search Engine Optimization). Suena complicado, pero lo básico es sencillo — y es completamente gratis." },
      { type: "heading", text: "Paso 1: Reclama y Completa Tu Perfil de Google Business" },
      { type: "paragraph", text: "Tu perfil de Google Business es el listado que aparece en Google Maps y en resultados locales. Si no lo has reclamado, ve a business.google.com y hazlo ya. Es gratis y es lo más importante que puedes hacer para visibilidad local." },
      { type: "list", items: [
        "Agrega el nombre de tu negocio, dirección, y teléfono — asegúrate que sean exactamente iguales a los de tu website.",
        "Elige las categorías correctas (ejemplo: 'Plumber,' 'HVAC Contractor,' 'Roofing Contractor').",
        "Agrega fotos de tu trabajo, tu truck, y tu equipo.",
        "Escribe una descripción que incluya tus servicios y las ciudades que atiendes.",
        "Agrega tus áreas de servicio y horarios de operación.",
      ]},
      { type: "callout", text: "\"Negocios con perfiles completos en Google reciben 7x más clicks que los incompletos. Completarlo toma 30 minutos — y es gratis.\""},
      { type: "heading", text: "Paso 2: Consigue Más Reviews" },
      { type: "paragraph", text: "El algoritmo de Google da mucho peso a la cantidad y calidad de tus reviews. Un negocio con 50 reviews casi siempre supera a uno con 5, aunque todo lo demás sea igual." },
      { type: "paragraph", text: "Pide a cada cliente feliz que deje un review en Google. Mándales el link directo por texto justo después de terminar el job. Apunta a 2-3 reviews nuevas por mes." },
      { type: "heading", text: "Paso 3: Mantén Tu Perfil Activo" },
      { type: "paragraph", text: "Google premia a negocios activos. Publica actualizaciones en tu perfil de Google Business al menos dos veces al mes — fotos de jobs recientes, promociones estacionales, o tips útiles. Esto le dice a Google que tu negocio es legítimo y está comprometido." },
      { type: "heading", text: "Paso 4: Asegúrate Que Tu Website Mencione Tu Ubicación" },
      { type: "paragraph", text: "Tu website debe mencionar claramente las ciudades y áreas que atiendes. Incluye frases como 'Contractor HVAC sirviendo Phoenix, Scottsdale, y Tempe' de forma natural en tus páginas. Esto ayuda a Google a entender dónde operas y mostrar tu negocio a la gente correcta." },
      { type: "tip", text: "Pro Tip: Crea una página separada en tu website para cada ciudad que atiendes. Una página titulada 'Servicios de Plomería en [Nombre de Ciudad]' con 300+ palabras sobre tus servicios en esa área puede subir mucho tu ranking para búsquedas en esa ciudad." },
      { type: "heading", text: "¿Cuánto Tiempo Toma?" },
      { type: "paragraph", text: "El SEO local no es instantáneo. Normalmente toma 3-6 meses de esfuerzo consistente para ver resultados significativos. Pero una vez que estás rankeando, los leads siguen llegando — sin pagar por ads. Es la inversión de marketing más costo-efectiva que un contractor puede hacer." },
    ],
  },
  {
    id: "7",
    slug: "stop-losing-repeat-business-how-to-keep-customers-coming-back",
    title: "Deja de Perder Clientes Recurrentes: Cómo Hacer Que Vuelvan",
    subtitle: "Tus clientes pasados son tu activo más valioso. La mayoría de contractors nunca los aprovechan.",
    category: "Customer Retention",
    readTime: "6 min read",
    date: "February 15, 2026",
    image: IMGS.plumber,
    imageAlt: "Plomero construyendo relación con cliente",
    excerpt: "Conseguir un cliente nuevo cuesta 5 veces más que mantener uno existente. Pero la mayoría de contractors pone toda su energía en nuevos leads y ignora la mina de oro que tienen en su lista de clientes.",
    content: [
      { type: "paragraph", text: "Aquí una pregunta: ¿Cuántos clientes has atendido en los últimos 5 años? Ahora, ¿de cuántos has sabido desde entonces? Si la respuesta es 'pocos,' estás dejando mucho dinero sobre la mesa." },
      { type: "paragraph", text: "El contractor promedio gasta la mayoría de su presupuesto de marketing tratando de encontrar nuevos clientes. Pero la investigación muestra consistentemente que cuesta 5 veces más adquirir un cliente nuevo que mantener uno existente. Y los clientes existentes tienen 67% más probabilidad de comprar de nuevo." },
      { type: "heading", text: "Por Qué Los Clientes No Vuelven (Aunque Te Amaron)" },
      { type: "paragraph", text: "No es que se fueron con la competencia. Es que se olvidaron de ti. La vida se puso ocupada. El problema se arregló. Siguieron adelante. Y cuando necesitaron un contractor otra vez seis meses después, volvieron a Google y encontraron a otro." },
      { type: "callout", text: "\"Cuesta 5x más adquirir un cliente nuevo que retener uno existente. Pero la mayoría de contractors gasta 90% de su presupuesto en adquirir nuevos clientes.\""},
      { type: "heading", text: "La Forma Simple de Mantenerte En La Mente" },
      { type: "paragraph", text: "No necesitas llamar a cada cliente pasado cada mes. Solo necesitas aparecer ocasionalmente de forma útil y sin ser molesto. Esto funciona:" },
      { type: "list", items: [
        "Un recordatorio estacional por email o texto (ejemplo: 'Hora de darle servicio a tu AC antes del verano — responde para reservar tu cita')",
        "Un mensaje de cumpleaños o festivo — un simple 'Feliz Día de Acción de Gracias de [Tu Empresa]' te mantiene en su mente",
        "Un chequeo anual ('Hace un año que instalamos tu calentador — ¿todo sigue funcionando bien?')",
        "Pedir referidos ('Si conoces a alguien que necesita plomero, nos encantaría la introducción')",
        "Una oferta especial para clientes pasados ('Como cliente valioso, aquí tienes 10% de descuento en tu próxima llamada de servicio')",
      ]},
      { type: "heading", text: "Cómo Hacer Esto Sin Que Tome Horas" },
      { type: "paragraph", text: "La clave es la automatización. No mandas estos mensajes manualmente — configuras un sistema una vez y corre en automático. Cuando llega el aniversario del cliente, el sistema manda el mensaje. Cuando llega la primavera, el recordatorio estacional se manda a toda tu lista." },
      { type: "paragraph", text: "Esto es exactamente lo que hace un sistema de re-activación de clientes. Lo configuras una vez, y mantiene tu nombre frente a cada cliente pasado, automáticamente, para siempre." },
      { type: "tip", text: "Pro Tip: Empieza simple. Exporta tu lista de clientes de tu software de facturación, agrégala a una lista básica de email, y manda un email por temporada. Incluso este enfoque básico puede generar miles de dólares en negocios recurrentes." },
      { type: "heading", text: "Los Números No Mienten" },
      { type: "paragraph", text: "Uno de nuestros contractors reactivó 200 clientes pasados en su primer mes usando una campaña automática. Reservaron $18,000 en jobs de clientes que no habían sabido de ellos en años. Eso no es gasto de marketing — es inversión con retorno claro." },
    ],
  },
  {
    id: "8",
    slug: "how-to-price-your-services-so-you-stop-competing-on-price",
    title: "Cómo Poner Precio a Tus Servicios Para Dejar de Competir Solo Por Precio",
    subtitle: "Los contractors que cobran más no siempre son los mejores. Son los que mejor hacen marketing.",
    category: "Business Growth",
    readTime: "7 min read",
    date: "February 8, 2026",
    image: IMGS.roofing,
    imageAlt: "Contractor de roofing trabajando en techo residencial",
    excerpt: "Si siempre pierdes jobs con competidores más baratos, el problema probablemente no sea tu precio. Es cómo presentas tu valor. Aquí te decimos cómo arreglarlo.",
    content: [
      { type: "paragraph", text: "Todo contractor ha estado ahí: das un presupuesto, el cliente dice 'Me dieron un precio más barato en otro lado,' y o bajas tu precio o pierdes el job. Es frustrante, y le pasa a casi todos en los trades." },
      { type: "paragraph", text: "Pero aquí está lo que la mayoría de contractors no entiende: los clientes no siempre eligen lo más barato. Eligen lo que se siente más seguro. Y 'seguro' se determina por qué tan profesional te ves, qué tan rápido respondes, y cuántas otras personas te han recomendado." },
      { type: "heading", text: "Por Qué Los Clientes Pagan Más Por El Mismo Servicio" },
      { type: "paragraph", text: "Piensa por qué pagarías más por un plomero que por otro. No es solo por habilidad — eso no lo sabes hasta después del job. Es por confianza. Pagas más por el que tiene mejores reviews, website más profesional, y truck más limpio." },
      { type: "callout", text: "\"Contractors con fuerte presencia online y 50+ reviews en Google pueden cobrar 20-30% más que competidores con presencia débil — y aún así ganar el job.\""},
      { type: "heading", text: "Las 3 Cosas Que Te Permiten Cobrar Más" },
      { type: "list", items: [
        "Reviews: Más reviews 5 estrellas = más confianza = menos sensibilidad al precio. Un contractor con 80 reviews puede cobrar más que uno con 8.",
        "Profesionalismo: Una website limpia y moderna, uniformes con marca, y un truck profesional muestran calidad antes de que llegues.",
        "Velocidad: Responder más rápido que la competencia muestra que eres organizado, confiable, y demandado — todo justifica precios más altos.",
      ]},
      { type: "heading", text: "Cómo Presentar Tu Precio Con Confianza" },
      { type: "paragraph", text: "Cuando das un presupuesto, no te disculpes por tu precio. Preséntalo con confianza y explica qué incluye. Los clientes que comparan precios usualmente comparan manzanas con naranjas — tu trabajo es mostrar por qué tu manzana vale más." },
      { type: "list", items: [
        "Desglosa tu presupuesto para que el cliente vea exactamente qué recibe",
        "Menciona tu garantía o respaldo desde el principio",
        "Refiere a tus reviews ('Tenemos 85 reviews cinco estrellas de homeowners como tú')",
        "Explica qué te diferencia ('Usamos materiales comerciales, no lo barato')",
      ]},
      { type: "tip", text: "Pro Tip: Nunca seas el primero en hablar de precio. Haz preguntas, entiende el problema del cliente, explica tu solución — y luego da el precio. Para cuando cotices, ya deberían sentir que eres la mejor opción." },
      { type: "heading", text: "La Conclusión" },
      { type: "paragraph", text: "No puedes competir bajando precio con el que siempre está más barato. Pero sí puedes ganarle en marketing. Construye tus reviews, luce profesional online, y responde rápido — y verás que los clientes dejan de preguntar por precio y empiezan a preguntar cuándo puedes empezar." },
    ],
  },
  {
    id: "9",
    slug: "the-contractors-guide-to-getting-jobs-from-facebook-and-instagram",
    title: "La Guía del Contractor Para Conseguir Jobs de Facebook e Instagram",
    subtitle: "No necesitas miles de seguidores. Solo necesitas que las personas correctas vean tu trabajo.",
    category: "Social Media",
    readTime: "6 min read",
    date: "February 1, 2026",
    image: IMGS.hvac,
    imageAlt: "Técnico HVAC trabajando en unidad residencial",
    excerpt: "La mayoría de contractors o ignoran social media o postean al azar y no sacan nada. Aquí el enfoque específico que realmente genera jobs desde Facebook e Instagram.",
    content: [
      { type: "paragraph", text: "Seamos claros: no necesitas ser experto en social media para conseguir jobs de Facebook e Instagram. No necesitas muchos seguidores. No necesitas postear todos los días. Solo necesitas mostrar tu trabajo a las personas correctas, consistentemente." },
      { type: "paragraph", text: "Los contractors que sacan más provecho de social media no son los que tienen más seguidores. Son los que aparecen consistentemente, postean trabajo real, y se involucran con su comunidad local." },
      { type: "heading", text: "Facebook: Donde Tus Clientes Realmente Están" },
      { type: "paragraph", text: "Para la mayoría de contractors locales, Facebook vale más que Instagram. ¿Por qué? Porque tus clientes — homeowners de 35 a 65 años — están más activos en Facebook. Y los grupos locales de Facebook son una mina de oro para contractors." },
      { type: "list", items: [
        "Únete a todos los grupos de vecindario y comunidad en Facebook de tu área de servicio.",
        "Cuando alguien pida recomendación de contractor, responde rápido con una intro breve y un link a tu perfil.",
        "Postea tus jobs terminados en esos grupos (donde esté permitido) — 'Acabamos de terminar esta remodelación de cocina en [vecindario], feliz de ayudar a quien necesite en la zona!'",
        "Corre un anuncio simple en Facebook dirigido a homeowners en tus códigos postales — hasta $5/día puede generar leads.",
      ]},
      { type: "callout", text: "\"Los grupos de vecindario en Facebook generan más referidos para contractors que cualquier otra plataforma social. Estar activo en solo 3-4 grupos locales puede sumar 5-10 jobs nuevos por mes.\""},
      { type: "heading", text: "Instagram: Construyendo Tu Portafolio Visual" },
      { type: "paragraph", text: "Instagram es tu portafolio visual. Es donde los clientes potenciales van a ver si tu trabajo es tan bueno como dices. La meta no es volverse viral — es tener un feed que se vea profesional y muestre un historial consistente de trabajo de calidad." },
      { type: "list", items: [
        "Postea fotos de antes y después de cada job — estas tienen el mayor engagement por mucho.",
        "Usa hashtags locales como #[TuCiudad]Plumber o #[TuCiudad]HVAC para llegar a homeowners locales.",
        "Agrega tu ubicación en cada post.",
        "Postea Stories en Instagram mostrando el trabajo en progreso — genera confianza y muestra tu proceso.",
      ]},
      { type: "heading", text: "La Única Cosa Que Hace Que Todo Funcione" },
      { type: "paragraph", text: "Consistencia. Postear 3 veces por semana durante 6 meses gana a postear 20 veces una semana y luego desaparecer. Pon un horario realista — hasta 2 posts por semana — y cúmplelo. Con el tiempo, construirás seguidores locales que te piensen primero cuando necesiten tus servicios." },
      { type: "tip", text: "Pro Tip: Pide a clientes felices que te etiqueten cuando posteen sobre su mejora en casa. El contenido generado por usuarios es la forma más confiable de prueba social, y no te cuesta nada." },
    ],
  },
  {
    id: "10",
    slug: "how-to-hire-and-keep-good-employees-as-a-growing-contractor",
    title: "Cómo Contratar y Mantener Buenos Empleados Como Contractor en Crecimiento",
    subtitle: "La escasez de mano de obra es real. Aquí cómo los mejores contractors están ganando la guerra por talento.",
    category: "Business Growth",
    readTime: "7 min read",
    date: "January 25, 2026",
    image: IMGS.leads,
    imageAlt: "Equipo de contractor trabajando juntos en un proyecto",
    excerpt: "Encontrar y mantener buenos tradespeople es uno de los mayores retos en la industria. Esto es lo que hacen diferente los negocios de trade mejor manejados para atraer y retener talento top.",
    content: [
      { type: "paragraph", text: "Pregunta a cualquier contractor cuál es su mayor reto, y la mayoría dirá lo mismo: encontrar buena gente. Los trades calificados tienen una grave escasez de mano de obra, y está empeorando. Pero algunos contractors parecen no tener problema para atraer y mantener empleados excelentes. ¿Qué hacen diferente?" },
      { type: "paragraph", text: "La respuesta usualmente se reduce a tres cosas: cómo presentan su empresa, cómo tratan a su gente, y cómo manejan su negocio." },
      { type: "heading", text: "Tu Presencia Online Afecta Quién Aplica Para Trabajar Contigo" },
      { type: "paragraph", text: "Antes de que un posible empleado aplique a un trabajo, te busca online. Revisa tus reviews en Google, tu website, y tu social media. Una empresa que se ve profesional y tiene buenas reviews es más atractiva para trabajar que una que parece estar batallando." },
      { type: "callout", text: "\"El 73% de quienes buscan trabajo investigan la reputación online de la empresa antes de aplicar. Una fuerte presencia online no solo atrae clientes — también atrae mejores empleados.\""},
      { type: "heading", text: "Qué Buscan Los Buenos Empleados" },
      { type: "paragraph", text: "El dinero importa, pero no es todo. Los mejores tradespeople tienen opciones — pueden trabajar en cualquier lado. Lo que buscan más allá del pago es:" },
      { type: "list", items: [
        "Trabajo estable y consistente — no quieren preocuparse por despidos cuando está lento",
        "Una empresa profesional y organizada — nadie quiere trabajar en caos",
        "Un jefe que respete sus habilidades y los trate como profesionales",
        "Caminos claros para avanzar — la oportunidad de ser lead tech o foreman",
        "Buen equipo y vehículos — es difícil hacer buen trabajo con malas herramientas",
      ]},
      { type: "heading", text: "Cómo Encontrar Buena Gente" },
      { type: "list", items: [
        "Publica jobs en Indeed y ZipRecruiter con descripciones claras y honestas",
        "Pide referidos a tus mejores empleados — ellos conocen a otros buenos tradespeople",
        "Haz alianzas con escuelas de trade locales y programas de aprendizaje",
        "Publica en grupos locales de Facebook y tablones comunitarios",
        "Ofrece bono por referido a empleados actuales que traigan nuevos hires",
      ]},
      { type: "heading", text: "Cómo Mantener Buena Gente Una Vez Que La Tienes" },
      { type: "paragraph", text: "Contratar es caro. Entrenar es caro. La rotación es el costo oculto más grande en la mayoría de negocios de trade. La mejor forma de mantener buenos empleados es simple: págales justo, trátalos con respeto, y dales las herramientas y apoyo que necesitan para hacer bien su trabajo." },
      { type: "tip", text: "Pro Tip: Haz un chequeo a los 90 días con cada nuevo empleado. Pregúntales qué va bien, qué les frustra, y qué haría su trabajo más fácil. La mayoría de empleados que renuncian lo hacen porque se sintieron ignorados — una simple conversación puede evitar eso." },
      { type: "heading", text: "La Conclusión" },
      { type: "paragraph", text: "Los contractors que ganan la guerra por talento son los que manejan negocios profesionales y organizados que la gente se siente orgullosa de trabajar. Eso empieza con cómo te presentas online, sigue con cómo manejas tus operaciones, y termina con cómo tratas a tu gente cada día." },
    ],
  },

  {
    id: "11",
    slug: "mindset-ai-marketing-trades",
    title: "La Mentalidad Que Separa a Los Contratistas Que Ganan con IA",
    subtitle: "Si crees que la IA 'no es para gente como yo,' este artículo es para ti.",
    category: "AI Marketing",
    readTime: "6 min read",
    date: "March 28, 2026",
    image: IMGS.mindset,
    imageAlt: "Equipo de contractor trabajando juntos en un proyecto",
    excerpt: "Los contratistas que ganan hoy no son los más tech-savvy. Son los que tienen la mentalidad correcta para invertir en lo que funciona. Aquí te contamos qué significa eso para tu negocio.",
    content: [
      { type: "paragraph", text: "Hay un momento que todo dueño de negocio de trades vive — el job site está ocupado, el teléfono no para de sonar, y en algún rincón de tu mente sabes que deberías estar haciendo más para mercadear tu negocio. Pero el marketing se siente complicado. La tecnología parece cosa de empresas grandes con presupuestos grandes. ¿Y la inteligencia artificial? Eso suena a ciencia ficción." },
      { type: "callout", text: "\"Los contratistas que están ganando ahorita no son los más expertos en tecnología. Son los que tienen la mentalidad correcta.\"" },
      { type: "heading", text: "La Lección de una Historia de Ventas Aprendida a las Malas" },
      { type: "paragraph", text: "Un líder de ventas compartió algo recientemente que nos hizo reflexionar. Dijo que durante años, su equipo cerraba contratos con cualquier dueño de negocio que apareciera — incluso cuando algo no se sentía bien. Superaban objeciones, convencían a dueños dudosos, y firmaban contratos. Y luego esos clientes se iban rápido, exigían resultados inmediatos, y amenazaban con cancelar en semanas." },
      { type: "paragraph", text: "¿El punto de quiebre? Dejaron de mirar qué hacía el negocio y empezaron a mirar cómo pensaba el dueño. Los dueños que se quedaban, crecían, y obtenían resultados reales eran los que llegaban con una sola creencia simple: 'Estoy dispuesto a invertir para ganar.' No 'demuéstramelo en 30 días o me voy.' Sino una apertura genuina a probar algo nuevo, confiar en el proceso, y darle tiempo para funcionar." },
      { type: "heading", text: "Lo Que Esto Significa Para Ti Como Contratista Latino" },
      { type: "paragraph", text: "Construiste tu negocio con tus manos. Te levantabas antes del amanecer, aprendiste un oficio, ganaste confianza trabajo por trabajo. Eso requirió determinación, disciplina, y la disposición de hacer lo que otros no harían. Ese mismo espíritu es exactamente lo que se necesita para ganar en la era de la IA." },
      { type: "paragraph", text: "No necesitas entender cómo funciona la IA. No necesitas estar en TikTok. No necesitas saber qué es un 'funnel.' Lo que necesitas es lo mismo que tenías cuando empezaste tu negocio: la disposición de invertir en algo que funciona, aunque todavía no lo entiendas completamente." },
      { type: "tip", text: "Piensa en cuando compraste tu primera troca nueva. No construiste el motor. Solo sabías: esta herramienta me va a ayudar a hacer más trabajo, más rápido. El marketing con IA es lo mismo." },
      { type: "heading", text: "La Ola de la IA Ya Está Aquí — Y No Está Esperando" },
      { type: "paragraph", text: "Tus competidores que tienen sitios web que aparecen en Google están recibiendo las llamadas que tú no estás recibiendo. Los contratistas con sistemas de seguimiento automatizado están cerrando leads que se enfrían para todos los demás. Los dueños de negocio con agentes de IA contestando su teléfono a las 11pm están agendando trabajos mientras tú duermes." },
      { type: "callout", text: "La pregunta no es si la IA va a afectar tu negocio. Ya lo está haciendo. La pregunta es: ¿vas a ser el contratista que se adaptó, o el que se quedó atrás?" },
      { type: "heading", text: "Los Dos Tipos de Contratistas Que Vemos" },
      { type: "paragraph", text: "Tipo 1 — El Escéptico: 'Llevo 20 años haciendo esto sin tecnología. Mi negocio funciona con referencias. No necesito esto.' Este contratista está ocupado hoy. Pero su pipeline es frágil. Una temporada lenta, una mala reseña, un competidor con mejor presencia en línea — y todo cambia." },
      { type: "paragraph", text: "Tipo 2 — El Inversionista: 'No lo entiendo completamente todavía, pero sé que necesito crecer. Dime cómo funciona.' Este contratista quizás no sea el más experto en tecnología. Pero es entrenable. Confía en el proceso. Y seis meses después, es el que nos llama para decirnos que su volumen de leads se duplicó." },
      { type: "callout", text: "La diferencia no es inteligencia. No es experiencia. Ni siquiera es presupuesto. Es mentalidad." },
      { type: "heading", text: "No Tienes Que Hacer Esto Solo" },
      { type: "paragraph", text: "En Contractor5x, construimos todo nuestro servicio para dueños de negocios de trades que son excelentes en su oficio pero que no fueron a la escuela para aprender marketing. Nosotros manejamos la IA, los sitios web, el seguimiento de leads, la presencia en Google — todo. Tu trabajo es aparecer, hacer un gran trabajo, y estar abierto al crecimiento." },
      { type: "paragraph", text: "No te estamos pidiendo que te conviertas en un experto en tecnología. Te estamos pidiendo que tengas el mismo valor que tuviste cuando empezaste tu negocio: apuesta por ti mismo, e invierte en lo que funciona. El mundo de la IA no viene por tu trabajo. Viene por tus competidores que no están listos para él. Asegúrate de estar del lado correcto de esa línea." },
    ],
  },
];