export interface BlogPost {
  id: string;
  slug: string;
  title: string;
  subtitle: string;
  category: string;
  readTime: string;
  date: string;
  image: string;
  imageAlt: string;
  excerpt: string;
  content: BlogSection[];
}

export interface BlogSection {
  type: "paragraph" | "heading" | "subheading" | "list" | "callout" | "tip";
  text?: string;
  items?: string[];
}

// Unsplash images — trade/contractor themed
const IMGS = {
  phone: "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=1200&q=80",
  google: "https://images.unsplash.com/photo-1573804633927-bfcbcd909acd?w=1200&q=80",
  reviews: "https://images.unsplash.com/photo-1600880292203-757bb62b4baf?w=1200&q=80",
  plumber: "https://images.unsplash.com/photo-1607472586893-edb57bdc0e39?w=1200&q=80",
  roofing: "https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=1200&q=80",
  hvac: "https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=1200&q=80",
  social: "https://images.unsplash.com/photo-1611162617213-7d7a39e9b1d7?w=1200&q=80",
  website: "https://images.unsplash.com/photo-1467232004584-a241de8bcf5d?w=1200&q=80",
  leads: "https://images.unsplash.com/photo-1553877522-43269d4ea984?w=1200&q=80",
  ai: "https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=1200&q=80",
};

export const blogPosts: BlogPost[] = [
  {
    id: "1",
    slug: "why-you-lose-leads-before-you-even-know-you-had-them",
    title: "Why You're Losing Leads Before You Even Know You Had Them",
    subtitle: "The #1 reason contractors lose jobs — and it has nothing to do with your price.",
    category: "Lead Generation",
    readTime: "5 min read",
    date: "March 20, 2026",
    image: IMGS.phone,
    imageAlt: "Contractor checking phone for missed calls",
    excerpt: "Most contractors think they lose jobs because of price. The real reason is response time. Here's what the data says — and what you can do about it today.",
    content: [
      { type: "paragraph", text: "Here's a scenario that plays out hundreds of times a day for contractors across the country: A homeowner needs their HVAC fixed. They go to Google, find three contractors, and send all three a message. The first one to respond gets the job. The other two never hear back." },
      { type: "paragraph", text: "That's not a guess. That's what the data shows. 78% of leads go to the first business that responds. And the average contractor takes over 2 hours to respond to a new inquiry — if they respond at all." },
      { type: "heading", text: "The Real Problem Isn't Your Price" },
      { type: "paragraph", text: "When contractors lose jobs, they usually blame price. 'The customer went with a cheaper guy.' But in most cases, the customer went with whoever called them back first. Price didn't even come up." },
      { type: "paragraph", text: "Think about it from the customer's side. They have a broken pipe. They're stressed. They send three messages. One contractor calls back in 10 minutes. The other two call back the next day. Who do you think they hire?" },
      { type: "callout", text: "\"78% of customers hire the first contractor who responds. The average response time for contractors is 2+ hours.\"" },
      { type: "heading", text: "Why Fast Response Is So Hard for Contractors" },
      { type: "paragraph", text: "You're not sitting at a desk waiting for inquiries. You're on a roof. You're under a sink. You're driving between jobs. Answering every call and message the moment it comes in is physically impossible when you're doing the actual work." },
      { type: "paragraph", text: "This is the fundamental problem with running a trade business — the same skills that make you great at your craft make it hard to run the business side. You can't be in two places at once." },
      { type: "heading", text: "What You Can Do About It" },
      { type: "paragraph", text: "The good news is this is a completely solvable problem — and you don't need to hire a receptionist or be glued to your phone to fix it." },
      { type: "list", items: [
        "Set up an automated text response that goes out the moment someone fills out your contact form — even if it's just 'Got your message, we'll call you within the hour.'",
        "Use a missed call text-back system so anyone who calls and doesn't reach you gets an instant text response.",
        "Consider an AI agent that can answer calls and messages 24/7, qualify leads, and book estimates on your calendar.",
        "At minimum, check your messages every 2 hours and respond within the same business day.",
      ]},
      { type: "tip", text: "Pro Tip: Even a simple automated text saying 'Thanks for reaching out! We'll call you back within the hour' can dramatically increase your close rate. It shows the customer you're responsive and professional — and it buys you time to finish the job you're on." },
      { type: "heading", text: "The Bottom Line" },
      { type: "paragraph", text: "You're probably doing great work. Your customers love you. But if you're not responding to new inquiries fast enough, you're leaving money on the table every single day. Fix your response time and watch your close rate go up — without changing anything else about how you do business." },
    ],
  },
  {
    id: "2",
    slug: "how-to-get-more-google-reviews-without-begging",
    title: "How to Get More Google Reviews Without Begging for Them",
    subtitle: "A simple system that gets you a steady stream of 5-star reviews — on autopilot.",
    category: "Google & Reviews",
    readTime: "6 min read",
    date: "March 15, 2026",
    image: IMGS.reviews,
    imageAlt: "Five star Google review on phone screen",
    excerpt: "Google reviews are the #1 factor in local search ranking. Here's a simple, repeatable system to get more of them without awkward conversations with customers.",
    content: [
      { type: "paragraph", text: "If you want more jobs from Google, you need more reviews. It's that simple. Google's algorithm looks at the number of reviews, the quality of reviews, and how recently you got them. A contractor with 80 reviews almost always outranks one with 8 — even if the one with 8 does better work." },
      { type: "paragraph", text: "The problem most contractors have isn't that their customers don't want to leave reviews. It's that they never ask — or they ask in a way that makes it feel awkward and complicated." },
      { type: "heading", text: "Why Customers Don't Leave Reviews (Even When They Love You)" },
      { type: "paragraph", text: "Your customers are busy. They had a great experience, they meant to leave a review, and then life got in the way. It's not that they don't want to — it's that it requires effort, and effort requires a reason." },
      { type: "paragraph", text: "The solution is to make it as easy as possible and ask at exactly the right moment." },
      { type: "callout", text: "\"88% of consumers trust online reviews as much as personal recommendations. Contractors with 50+ reviews get 3x more calls than those with fewer than 10.\"" },
      { type: "heading", text: "The Right Moment to Ask" },
      { type: "paragraph", text: "The best time to ask for a review is right after you finish a job — when the customer is happiest. This is when they just saw your work, they're relieved the problem is solved, and they feel good about the money they spent." },
      { type: "paragraph", text: "Don't wait a week. Don't send an email three days later. Ask right then, in person or via text within an hour of completing the job." },
      { type: "heading", text: "The Simple Script That Works" },
      { type: "paragraph", text: "In person, at the end of the job, say this: 'Hey [name], I'm really glad we could take care of that for you. If you have 60 seconds, a Google review would mean the world to us — it helps other homeowners find us. I'll text you the link right now.'" },
      { type: "paragraph", text: "Then pull out your phone and text them the direct link to your Google review page. Done." },
      { type: "list", items: [
        "Create a short link to your Google review page (Google it — it takes 2 minutes to set up).",
        "Save it in your phone as a text template so you can send it with one tap.",
        "Send it within 30 minutes of finishing the job while the experience is fresh.",
        "Follow up once, 48 hours later, if they haven't left one yet.",
      ]},
      { type: "tip", text: "Pro Tip: Never ask for a '5-star review.' Just ask for 'an honest review.' This feels less pushy and actually results in more reviews — and they're almost always 5 stars if you did good work." },
      { type: "heading", text: "Automate It So You Never Forget" },
      { type: "paragraph", text: "The best contractors don't rely on remembering to ask. They have a system that automatically sends a review request text after every completed job. This way, every customer gets asked — not just the ones you remember to ask." },
      { type: "paragraph", text: "With a system like this, a contractor doing 5 jobs a week could realistically add 100+ new reviews per year. That's the difference between page 3 and the top 3 on Google." },
    ],
  },
  {
    id: "3",
    slug: "the-truth-about-contractor-websites-that-nobody-tells-you",
    title: "The Truth About Contractor Websites That Nobody Tells You",
    subtitle: "Most contractor websites are actively costing you jobs. Here's why — and what a good one actually looks like.",
    category: "Website & SEO",
    readTime: "7 min read",
    date: "March 10, 2026",
    image: IMGS.website,
    imageAlt: "Contractor website on laptop screen",
    excerpt: "Having a website isn't enough. A bad website can actually hurt you more than having no website at all. Here's what separates a website that generates leads from one that doesn't.",
    content: [
      { type: "paragraph", text: "Most contractors have a website. Very few have a website that actually works. There's a big difference between having a website and having a website that brings in leads, builds trust, and converts visitors into paying customers." },
      { type: "paragraph", text: "The hard truth is that a bad website can actually hurt you. If a potential customer visits your site and it looks outdated, loads slowly, or doesn't work on their phone — they're gone. And they're probably going to your competitor." },
      { type: "heading", text: "What Customers Are Doing Before They Call You" },
      { type: "paragraph", text: "75% of people judge a business's credibility based on their website. Before they pick up the phone, they're looking at your site, reading your reviews, and comparing you to your competitors. You have about 0.05 seconds to make a first impression." },
      { type: "callout", text: "\"75% of consumers judge a company's credibility based on their website design. You have 0.05 seconds to make a first impression.\"" },
      { type: "heading", text: "The 5 Things a Contractor Website Must Have" },
      { type: "list", items: [
        "A clear headline that says exactly what you do and where you do it — 'HVAC Repair & Installation in Phoenix, AZ' not just 'Welcome to Our Website.'",
        "Real photos of your actual work — not stock photos. Customers want to see what you've done, not a generic image of a wrench.",
        "Your phone number visible at the top of every page, large enough to tap on a phone.",
        "Reviews and testimonials from real customers — ideally pulled directly from Google.",
        "A simple contact form or booking button that works on mobile.",
      ]},
      { type: "heading", text: "Why Mobile Matters More Than You Think" },
      { type: "paragraph", text: "Over 60% of searches for local contractors happen on a phone. If your website doesn't look good and work perfectly on a phone, you're losing more than half your potential customers before they even read a word." },
      { type: "paragraph", text: "Test your own website right now. Pull it up on your phone. Does it load fast? Is the text readable without zooming? Can you tap the phone number to call? If the answer to any of these is no, you have a problem." },
      { type: "heading", text: "The SEO Factor" },
      { type: "paragraph", text: "Your website also needs to be findable. This means it needs to be optimized for local search — the right keywords, the right structure, and regular updates. A website that never changes is a website that Google stops caring about." },
      { type: "tip", text: "Pro Tip: Add a new page or blog post to your website at least once a month. It doesn't have to be long — even 300 words about a recent project or a common customer question signals to Google that your site is active and relevant." },
      { type: "heading", text: "The Bottom Line" },
      { type: "paragraph", text: "Your website is your most important marketing asset. It works 24/7, it's the first thing customers see, and it either builds trust or destroys it. Investing in a good website isn't a luxury — it's the foundation of every other marketing effort you do." },
    ],
  },
  {
    id: "4",
    slug: "how-to-use-social-media-as-a-contractor-without-wasting-time",
    title: "How to Use Social Media as a Contractor Without Wasting Hours",
    subtitle: "You don't need to become an influencer. You just need a simple system that works.",
    category: "Social Media",
    readTime: "6 min read",
    date: "March 5, 2026",
    image: IMGS.social,
    imageAlt: "Contractor posting job photos on social media",
    excerpt: "Most contractors either ignore social media or spend too much time on it with nothing to show. Here's the simple, low-effort approach that actually brings in jobs.",
    content: [
      { type: "paragraph", text: "When contractors think about social media, they usually have one of two reactions: 'I don't have time for that' or 'I tried it and it didn't work.' Both reactions make sense — because most advice about social media is designed for influencers, not for someone who spends their day fixing roofs." },
      { type: "paragraph", text: "Here's the truth: you don't need to post every day. You don't need to dance on TikTok. You don't need a content strategy or a brand voice. You just need to show your work consistently, and let the quality of what you do speak for itself." },
      { type: "heading", text: "Why Social Media Actually Matters for Contractors" },
      { type: "paragraph", text: "Before hiring a contractor, most homeowners do some research. They check Google reviews, they look at your website, and — increasingly — they check your social media. Not to see if you're entertaining, but to see if you're real, if you do good work, and if other people have had good experiences with you." },
      { type: "callout", text: "\"93% of homeowners check online presence before hiring a contractor. Social media is now part of that research process.\"" },
      { type: "heading", text: "The Simple System That Works" },
      { type: "paragraph", text: "The only social media strategy you need as a contractor is this: post photos of your work, before and after when possible, with a short description of what you did and where. That's it." },
      { type: "list", items: [
        "Take 3-5 photos at every job — before you start, during, and after.",
        "Post one photo per job to Instagram and Facebook with a 2-3 sentence caption.",
        "Include your city and service in the caption for local SEO benefit.",
        "Respond to every comment, even just with a thumbs up.",
        "Post consistently — 2-3 times per week is better than 10 times one week and nothing for a month.",
      ]},
      { type: "heading", text: "What to Post When You Don't Have New Photos" },
      { type: "paragraph", text: "Some weeks are slow. Some jobs aren't photogenic. Here's what to post when you don't have fresh content:" },
      { type: "list", items: [
        "A tip or piece of advice for homeowners (e.g., 'Change your HVAC filter every 3 months to avoid costly repairs')",
        "A before/after from a previous job",
        "A customer testimonial or review",
        "A photo of your truck or team at a job site",
        "A question for your followers ('What's the most common plumbing problem in your area?')",
      ]},
      { type: "tip", text: "Pro Tip: The easiest way to stay consistent on social media is to batch your content. At the end of each week, spend 20 minutes writing captions for all the photos you took that week and schedule them to post automatically. Tools like Buffer or Later make this simple." },
      { type: "heading", text: "The Bottom Line" },
      { type: "paragraph", text: "Social media for contractors isn't about going viral. It's about being visible, looking professional, and building a track record of completed work that potential customers can see. A consistent, simple approach beats an elaborate strategy you never stick to." },
    ],
  },
  {
    id: "5",
    slug: "what-is-ai-marketing-and-why-every-contractor-needs-it-in-2026",
    title: "What Is AI Marketing — And Why Every Contractor Needs It in 2026",
    subtitle: "AI isn't just for tech companies. Here's how it's changing the game for local trade businesses.",
    category: "AI Marketing",
    readTime: "7 min read",
    date: "February 28, 2026",
    image: IMGS.ai,
    imageAlt: "AI technology concept for small business marketing",
    excerpt: "You've heard about AI. But what does it actually mean for your plumbing, HVAC, or roofing business? Here's a plain-English explanation of what AI marketing is and why it matters for you.",
    content: [
      { type: "paragraph", text: "Every week, there's a new headline about AI. It can feel overwhelming — especially when you're running a trade business and you just want to focus on doing great work. But here's the thing: AI is already changing how customers find and hire contractors, and if you're not paying attention, your competitors are going to get ahead of you." },
      { type: "paragraph", text: "The good news is you don't need to understand how AI works to benefit from it. You just need to understand what it can do for your business." },
      { type: "heading", text: "What AI Marketing Actually Means" },
      { type: "paragraph", text: "AI marketing means using software that can think, learn, and act — without you having to tell it what to do every time. Instead of you manually following up with every lead, responding to every review, or posting on social media, AI does it automatically." },
      { type: "paragraph", text: "Think of it like having a full marketing team working for you 24/7 — one that never sleeps, never forgets, and never has a bad day." },
      { type: "callout", text: "\"Contractors using AI marketing tools see an average of 3x more leads and 40% higher revenue within the first 6 months.\"" },
      { type: "heading", text: "The 5 Ways AI Is Already Helping Contractors" },
      { type: "list", items: [
        "Answering calls and messages instantly, 24/7 — even when you're on a job site",
        "Following up with leads automatically so none fall through the cracks",
        "Generating and responding to Google reviews without you lifting a finger",
        "Posting your work on social media consistently, every week",
        "Keeping past customers engaged with seasonal offers and reminders",
      ]},
      { type: "heading", text: "Is This Complicated to Set Up?" },
      { type: "paragraph", text: "This is the question we hear most often. And the honest answer is: it depends on who sets it up. If you try to piece together different software tools yourself, yes — it can be complicated and time-consuming." },
      { type: "paragraph", text: "But if you work with a company that specializes in AI marketing for contractors, they handle all the technical setup. You just show up and do the work you love. The AI handles the rest." },
      { type: "tip", text: "Pro Tip: You don't need to understand AI to use it. You don't understand how your truck's engine works, but you still drive it to every job. AI marketing tools are the same — you just need to know what they do, not how they do it." },
      { type: "heading", text: "The Contractors Who Will Win in 2026" },
      { type: "paragraph", text: "The contractors who thrive in the next few years won't necessarily be the ones with the most skills or the lowest prices. They'll be the ones who respond fastest, look most professional online, and have systems that work even when they're busy." },
      { type: "paragraph", text: "AI marketing is how you build those systems without hiring a full marketing team. And the sooner you start, the bigger the head start you'll have over competitors who are still doing everything manually." },
    ],
  },
  {
    id: "6",
    slug: "how-to-get-your-plumbing-business-to-show-up-on-google",
    title: "How to Get Your Trade Business to Show Up on Google",
    subtitle: "A plain-English guide to local SEO for contractors who aren't tech-savvy.",
    category: "Google & Reviews",
    readTime: "8 min read",
    date: "February 22, 2026",
    image: IMGS.google,
    imageAlt: "Google search results on laptop for local contractor",
    excerpt: "Showing up on Google when someone searches for your service in your area is the most valuable marketing you can do. Here's exactly how it works and what you need to do.",
    content: [
      { type: "paragraph", text: "When someone in your area searches 'HVAC repair near me' or 'emergency plumber [your city],' Google shows them a list of local businesses. The ones at the top get most of the calls. The ones on page 2 get almost none." },
      { type: "paragraph", text: "Getting your business to show up in those top results is called local SEO (Search Engine Optimization). It sounds complicated, but the basics are straightforward — and they're completely free to do." },
      { type: "heading", text: "Step 1: Claim and Complete Your Google Business Profile" },
      { type: "paragraph", text: "Your Google Business Profile is the listing that shows up on Google Maps and in local search results. If you haven't claimed yours yet, go to business.google.com and do it right now. It's free and it's the single most important thing you can do for local visibility." },
      { type: "list", items: [
        "Add your business name, address, and phone number — make sure they're exactly the same as on your website.",
        "Choose the right business categories (e.g., 'Plumber,' 'HVAC Contractor,' 'Roofing Contractor').",
        "Add photos of your work, your truck, and your team.",
        "Write a description that includes your services and the cities you serve.",
        "Add your service areas and hours of operation.",
      ]},
      { type: "callout", text: "\"Businesses with complete Google profiles get 7x more clicks than those with incomplete ones. It takes 30 minutes to complete — and it's free.\"" },
      { type: "heading", text: "Step 2: Get More Reviews" },
      { type: "paragraph", text: "Google's algorithm heavily weights the number and quality of your reviews. A business with 50 reviews almost always outranks one with 5, even if everything else is equal." },
      { type: "paragraph", text: "Ask every happy customer to leave a Google review. Text them the direct link right after you finish the job. Aim for at least 2-3 new reviews per month." },
      { type: "heading", text: "Step 3: Keep Your Profile Active" },
      { type: "paragraph", text: "Google rewards businesses that are active. Post updates to your Google Business Profile at least twice a month — photos of recent jobs, seasonal promotions, or helpful tips. This signals to Google that your business is legitimate and engaged." },
      { type: "heading", text: "Step 4: Make Sure Your Website Mentions Your Location" },
      { type: "paragraph", text: "Your website should clearly mention the cities and areas you serve. Include phrases like 'HVAC contractor serving Phoenix, Scottsdale, and Tempe' naturally throughout your pages. This helps Google understand where you operate and show you to the right people." },
      { type: "tip", text: "Pro Tip: Create a separate page on your website for each city you serve. A page titled 'Plumbing Services in [City Name]' with 300+ words about your services in that area can significantly boost your ranking for searches in that city." },
      { type: "heading", text: "How Long Does It Take?" },
      { type: "paragraph", text: "Local SEO isn't instant. It typically takes 3-6 months of consistent effort to see significant results. But once you're ranking, the leads keep coming — without paying for ads. It's the most cost-effective marketing investment a contractor can make." },
    ],
  },
  {
    id: "7",
    slug: "stop-losing-repeat-business-how-to-keep-customers-coming-back",
    title: "Stop Losing Repeat Business: How to Keep Customers Coming Back",
    subtitle: "Your past customers are your most valuable asset. Most contractors never tap into them.",
    category: "Customer Retention",
    readTime: "6 min read",
    date: "February 15, 2026",
    image: IMGS.plumber,
    imageAlt: "Plumber building customer relationship",
    excerpt: "Getting a new customer costs 5x more than keeping an existing one. Yet most contractors focus all their energy on new leads and ignore the goldmine sitting in their customer list.",
    content: [
      { type: "paragraph", text: "Here's a question: How many customers have you served in the last 5 years? Now, how many of them have you heard from since? If the answer is 'not many,' you're leaving a lot of money on the table." },
      { type: "paragraph", text: "The average contractor spends most of their marketing budget trying to find new customers. But research consistently shows that it costs 5 times more to acquire a new customer than to keep an existing one. And existing customers are 67% more likely to buy from you again." },
      { type: "heading", text: "Why Customers Don't Come Back (Even When They Loved You)" },
      { type: "paragraph", text: "It's not that they went to a competitor. It's that they forgot about you. Life got busy. The problem got fixed. They moved on. And when they needed a contractor again six months later, they went back to Google and found someone else." },
      { type: "callout", text: "\"It costs 5x more to acquire a new customer than to retain an existing one. Yet most contractors spend 90% of their marketing budget on new customer acquisition.\"" },
      { type: "heading", text: "The Simple Way to Stay Top of Mind" },
      { type: "paragraph", text: "You don't need to call every past customer every month. You just need to show up occasionally in a way that's helpful and not annoying. Here's what works:" },
      { type: "list", items: [
        "A seasonal reminder email or text (e.g., 'Time to get your AC serviced before summer — reply to book your spot')",
        "A birthday or holiday message — just a simple 'Happy Thanksgiving from [Your Company]' keeps you in their mind",
        "An annual check-in ('It's been a year since we installed your water heater — everything still running great?')",
        "A referral ask ('If you know anyone who needs a plumber, we'd love the introduction')",
        "A special offer for past customers ('As a valued customer, here's 10% off your next service call')",
      ]},
      { type: "heading", text: "How to Do This Without It Taking Hours" },
      { type: "paragraph", text: "The key is automation. You don't manually send these messages — you set up a system once and it runs on autopilot. When a customer's anniversary comes up, the system sends the message. When spring arrives, the seasonal reminder goes out to your whole list." },
      { type: "paragraph", text: "This is exactly what a customer re-activation system does. You set it up once, and it keeps your name in front of every past customer, automatically, forever." },
      { type: "tip", text: "Pro Tip: Start simple. Export your customer list from your invoicing software, add them to a basic email list, and send one email per season. Even this basic approach can generate thousands of dollars in repeat business." },
      { type: "heading", text: "The Numbers Don't Lie" },
      { type: "paragraph", text: "One of our contractors re-engaged 200 past customers in their first month using an automated re-activation campaign. They booked $18,000 in jobs from customers they hadn't heard from in years. That's not a marketing expense — that's a marketing investment with a clear return." },
    ],
  },
  {
    id: "8",
    slug: "how-to-price-your-services-so-you-stop-competing-on-price",
    title: "How to Price Your Services So You Stop Competing on Price",
    subtitle: "The contractors who charge the most aren't always the best. They're the ones who market the best.",
    category: "Business Growth",
    readTime: "7 min read",
    date: "February 8, 2026",
    image: IMGS.roofing,
    imageAlt: "Roofing contractor at work on residential roof",
    excerpt: "If you're constantly losing jobs to cheaper competitors, the problem probably isn't your price. It's how you're presenting your value. Here's how to fix it.",
    content: [
      { type: "paragraph", text: "Every contractor has been there: you give a quote, the customer says 'I got a cheaper price from someone else,' and you either drop your price or lose the job. It's frustrating, and it happens to almost everyone in the trades." },
      { type: "paragraph", text: "But here's what most contractors don't realize: customers don't always go with the cheapest option. They go with the option that feels the safest. And 'safe' is determined by how professional you look, how quickly you respond, and how many other people have vouched for you." },
      { type: "heading", text: "Why Customers Pay More for the Same Service" },
      { type: "paragraph", text: "Think about why you might pay more for one plumber over another. It's not just about skill — you can't really judge that until after the job. It's about trust. You pay more for the one with better reviews, a more professional website, and a cleaner truck." },
      { type: "callout", text: "\"Contractors with strong online presence and 50+ Google reviews can charge 20-30% more than competitors with weak online presence — and still win the job.\"" },
      { type: "heading", text: "The 3 Things That Let You Charge More" },
      { type: "list", items: [
        "Reviews: More 5-star reviews = more trust = less price sensitivity. A contractor with 80 reviews can charge more than one with 8.",
        "Professionalism: A clean, modern website, branded uniforms, and a professional truck wrap signal quality before you even show up.",
        "Speed: Responding faster than competitors signals that you're organized, reliable, and in demand — all of which justify higher prices.",
      ]},
      { type: "heading", text: "How to Present Your Price With Confidence" },
      { type: "paragraph", text: "When you give a quote, don't apologize for your price. Present it with confidence and explain what's included. Customers who are comparing prices are usually comparing apples to oranges — your job is to show them why your apple is worth more." },
      { type: "list", items: [
        "Itemize your quote so customers can see exactly what they're getting",
        "Mention your warranty or guarantee upfront",
        "Reference your reviews ('We have 85 five-star reviews from homeowners just like you')",
        "Explain what sets you apart ('We use commercial-grade materials, not the cheap stuff')",
      ]},
      { type: "tip", text: "Pro Tip: Never be the first to bring up price. Ask questions, understand the customer's problem, explain your solution — then give the price. By the time you quote, they should already feel like you're the right choice." },
      { type: "heading", text: "The Bottom Line" },
      { type: "paragraph", text: "You can't out-cheap the guy who's undercutting you. But you can out-market him. Build your reviews, look professional online, and respond fast — and you'll find that customers stop asking about price and start asking when you can start." },
    ],
  },
  {
    id: "9",
    slug: "the-contractors-guide-to-getting-jobs-from-facebook-and-instagram",
    title: "The Contractor's Guide to Getting Jobs from Facebook and Instagram",
    subtitle: "You don't need thousands of followers. You just need the right people to see your work.",
    category: "Social Media",
    readTime: "6 min read",
    date: "February 1, 2026",
    image: IMGS.hvac,
    imageAlt: "HVAC technician at work on residential unit",
    excerpt: "Most contractors either skip social media entirely or post randomly and get nothing from it. Here's the specific approach that actually generates jobs from Facebook and Instagram.",
    content: [
      { type: "paragraph", text: "Let's be clear about something: you don't need to be a social media expert to get jobs from Facebook and Instagram. You don't need a huge following. You don't need to post every day. You just need to show your work to the right people, consistently." },
      { type: "paragraph", text: "The contractors who get the most from social media aren't the ones with the most followers. They're the ones who show up consistently, post real work, and engage with their local community." },
      { type: "heading", text: "Facebook: Where Your Customers Actually Are" },
      { type: "paragraph", text: "For most local contractors, Facebook is more valuable than Instagram. Why? Because your customers — homeowners aged 35-65 — are more active on Facebook. And Facebook's local groups are a goldmine for contractors." },
      { type: "list", items: [
        "Join every local neighborhood and community Facebook group in your service area.",
        "When someone asks for a contractor recommendation, respond immediately with a brief intro and a link to your profile.",
        "Post your completed jobs to these groups (where allowed) — 'Just finished this kitchen remodel in [neighborhood], happy to help anyone else in the area!'",
        "Run a simple Facebook ad targeting homeowners in your zip codes — even $5/day can generate leads.",
      ]},
      { type: "callout", text: "\"Facebook neighborhood groups generate more contractor referrals than any other social platform. Being active in just 3-4 local groups can add 5-10 new jobs per month.\"" },
      { type: "heading", text: "Instagram: Building Your Visual Portfolio" },
      { type: "paragraph", text: "Instagram is your visual portfolio. It's where potential customers go to see if your work is as good as you say it is. The goal isn't to go viral — it's to have a feed that looks professional and shows a consistent track record of quality work." },
      { type: "list", items: [
        "Post before/after photos of every job — these get the most engagement by far.",
        "Use local hashtags like #[YourCity]Plumber or #[YourCity]HVAC to reach local homeowners.",
        "Add your location to every post.",
        "Post Instagram Stories showing the work in progress — it builds trust and shows your process.",
      ]},
      { type: "heading", text: "The One Thing That Makes Everything Work" },
      { type: "paragraph", text: "Consistency. Posting 3 times a week for 6 months beats posting 20 times in one week and then going silent. Set a realistic schedule — even 2 posts per week — and stick to it. Over time, you'll build a following of local homeowners who think of you first when they need your services." },
      { type: "tip", text: "Pro Tip: Ask happy customers to tag you when they post about their home improvement. User-generated content is the most trusted form of social proof, and it costs you nothing." },
    ],
  },
  {
    id: "10",
    slug: "how-to-hire-and-keep-good-employees-as-a-growing-contractor",
    title: "How to Hire and Keep Good Employees as a Growing Contractor",
    subtitle: "The labor shortage is real. Here's how the best contractors are winning the talent war.",
    category: "Business Growth",
    readTime: "7 min read",
    date: "January 25, 2026",
    image: IMGS.leads,
    imageAlt: "Contractor team working together on a project",
    excerpt: "Finding and keeping good tradespeople is one of the biggest challenges in the industry. Here's what the best-run trade businesses are doing differently to attract and retain top talent.",
    content: [
      { type: "paragraph", text: "Ask any contractor what their biggest challenge is, and most will say the same thing: finding good people. The skilled trades have a serious labor shortage, and it's getting worse. But some contractors seem to have no trouble attracting and keeping great employees. What are they doing differently?" },
      { type: "paragraph", text: "The answer usually comes down to three things: how they present their company, how they treat their people, and how they run their business." },
      { type: "heading", text: "Your Online Presence Affects Who Applies to Work for You" },
      { type: "paragraph", text: "Before a potential employee applies for a job, they look you up online. They check your Google reviews, your website, and your social media. A company that looks professional and has great reviews is more attractive to work for than one that looks like it's struggling." },
      { type: "callout", text: "\"73% of job seekers research a company's online reputation before applying. A strong online presence doesn't just attract customers — it attracts better employees.\"" },
      { type: "heading", text: "What Good Employees Are Looking For" },
      { type: "paragraph", text: "Money matters, but it's not everything. The best tradespeople have options — they can work anywhere. What they're looking for beyond pay is:" },
      { type: "list", items: [
        "Steady, consistent work — they don't want to worry about being laid off when it's slow",
        "A professional, organized company — nobody wants to work for chaos",
        "A boss who respects their skills and treats them like professionals",
        "Clear paths to advancement — the chance to become a lead tech or foreman",
        "Good equipment and vehicles — it's hard to do good work with bad tools",
      ]},
      { type: "heading", text: "How to Find Good People" },
      { type: "list", items: [
        "Post jobs on Indeed and ZipRecruiter with a clear, honest job description",
        "Ask your best employees for referrals — they know other good tradespeople",
        "Partner with local trade schools and apprenticeship programs",
        "Post on local Facebook groups and community boards",
        "Offer a referral bonus to current employees who bring in new hires",
      ]},
      { type: "heading", text: "How to Keep Good People Once You Have Them" },
      { type: "paragraph", text: "Hiring is expensive. Training is expensive. Turnover is the biggest hidden cost in most trade businesses. The best way to keep good employees is simple: pay them fairly, treat them with respect, and give them the tools and support they need to do their job well." },
      { type: "tip", text: "Pro Tip: Do a 90-day check-in with every new employee. Ask them what's going well, what's frustrating, and what would make their job easier. Most employees who quit do so because they felt unheard — a simple conversation can prevent that." },
      { type: "heading", text: "The Bottom Line" },
      { type: "paragraph", text: "The contractors who win the talent war are the ones who run professional, organized businesses that people are proud to work for. That starts with how you present yourself online, extends to how you run your operations, and ends with how you treat your people every day." },
    ],
  },
];
