import { Zap, Camera, Bot, Globe, RefreshCw, Star } from "lucide-react";
import type { SolutionData } from "@/components/SolutionPage";

const AI_DASHBOARD = "https://d2xsxph8kpxj0f.cloudfront.net/310519663485111386/DggHMYqYmKSoMpB2pB5sTZ/ai-dashboard-ZQvQg4K9jvT4urMpz8tHsh.webp";
const LEAD_CLOSER = "https://d2xsxph8kpxj0f.cloudfront.net/310519663485111386/DggHMYqYmKSoMpB2pB5sTZ/lead-closer-2mGVu2toi2ThpCWjbnyWaU.webp";
const CONTRACTOR_WORK = "https://d2xsxph8kpxj0f.cloudfront.net/310519663485111386/DggHMYqYmKSoMpB2pB5sTZ/contractor-work-n3H8tibW5po8kuFCJYpTqK.webp";
const GOOGLE_REVIEWS = "https://d2xsxph8kpxj0f.cloudfront.net/310519663485111386/DggHMYqYmKSoMpB2pB5sTZ/google-reviews-NjJWK5X2ixFWSDXEKDaQGJ.webp";

export const solutionsData: SolutionData[] = [
  {
    id: "lead-closer",
    number: "01",
    icon: Zap,
    label: "Your 24/7 Sales Machine",
    title: "Lead Closer",
    tagline: "Never lose a lead to a competitor again.",
    quote: '"You\'re out on a job site, covered in drywall dust, and your phone buzzes with 3 new quote requests. By the time you get home, those leads have already called your competitor."',
    heroDesc: "Lead Closer is your always-on sales machine — it responds to every inquiry within minutes, qualifies leads automatically, and keeps them warm until you're ready to close. Your pipeline stays full while you focus on the job.",
    desc: "Lead Closer responds instantly, qualifies leads, and keeps them warm until you're ready to close. Your pipeline stays full while you focus on the work you love.",
    stats: [
      { value: "78%", label: "of leads go to first responder" },
      { value: "5 min", label: "optimal response time" },
      { value: "3X", label: "more conversions" },
    ],
    features: [
      "Smart Pipeline Dashboard",
      "Custom Branded Intake Forms",
      "Two-way SMS & Call Tracking",
      "Automated Drip Campaigns",
      "Set-and-Forget Workflows",
      "Email & SMS Outreach",
    ],
    benefits: [
      { title: "Instant Lead Response", desc: "Every new inquiry gets an automated, personalized response within minutes — even at 2am on a Sunday." },
      { title: "Smart Lead Qualification", desc: "AI filters out tire-kickers and surfaces your hottest prospects so you only spend time on leads that are ready to buy." },
      { title: "Automated Follow-Up Sequences", desc: "Multi-touch drip campaigns keep leads warm over days and weeks until they're ready to book — without any manual effort." },
      { title: "Full Pipeline Visibility", desc: "See every lead, where they are in the funnel, and what action to take next — all in one clean dashboard." },
    ],
    howItWorks: [
      { step: "01", title: "Lead Comes In", desc: "A prospect fills out your form, calls, or messages you on any channel — web, social, or Google." },
      { step: "02", title: "AI Responds Instantly", desc: "Lead Closer sends a personalized response within minutes, qualifies the lead, and books a call or estimate." },
      { step: "03", title: "You Close the Deal", desc: "You get a hot, pre-qualified lead notification. You show up, close the job, and get paid." },
    ],
    image: LEAD_CLOSER,
    imageAlt: "Contractor checking leads on phone at job site",
  },
  {
    id: "job-promoter",
    number: "02",
    icon: Camera,
    label: "Your Work Speaks — We Make It Loud",
    title: "Job Promoter",
    tagline: "Your craftsmanship finally gets the attention it deserves.",
    quote: '"Your Instagram is empty. Your website shows work from 3 years ago. Meanwhile, a competitor with half your skill is booking jobs because they look more professional online."',
    heroDesc: "Job Promoter turns your completed projects into a powerful marketing engine — professional photos, cinematic videos, and before/after showcases distributed across every platform that matters to your customers.",
    desc: "We capture your best work with professional lookbooks, videos, and before/afters — then distribute them across every platform that matters.",
    stats: [
      { value: "93%", label: "check reviews before hiring" },
      { value: "4X", label: "more engagement with video" },
      { value: "87%", label: "trust visuals over text" },
    ],
    features: [
      "Magazine-Quality Lookbooks",
      "Organized Photo Gallery",
      "Detailed Case Studies",
      "SEO & AI Optimization",
      "Up to 25 Videos/Month",
      "Consistent Social Posting",
    ],
    benefits: [
      { title: "Professional Visual Content", desc: "We transform your job site photos into polished, magazine-quality visuals that make customers trust you before they even call." },
      { title: "Video That Converts", desc: "Short-form videos of your work get 4x more engagement than photos — we produce up to 25 per month, fully branded." },
      { title: "Automated Social Posting", desc: "Your best work goes out consistently across Instagram, Facebook, and Google — without you lifting a finger." },
      { title: "SEO-Optimized Showcases", desc: "Every project page is optimized to rank in local search, bringing in organic leads from people searching for your exact services." },
    ],
    howItWorks: [
      { step: "01", title: "You Send Us Your Photos", desc: "After each job, snap photos on your phone and send them to us. That's your only job." },
      { step: "02", title: "We Create the Content", desc: "Our team transforms your raw photos into professional lookbooks, videos, and social posts — fully branded." },
      { step: "03", title: "We Distribute Everywhere", desc: "Content goes live on your website, social channels, and Google listing — building your reputation on autopilot." },
    ],
    image: CONTRACTOR_WORK,
    imageAlt: "Professional contractors at work on residential project",
  },
  {
    id: "ai-agent",
    number: "03",
    icon: Bot,
    label: "Never Miss Another Call",
    title: "AI Agent",
    tagline: "Every call answered. Every lead captured. 24/7.",
    quote: '"You can\'t answer every call when you\'re 20 feet up on a ladder or knee-deep in a renovation. But every missed call is money walking out the door."',
    heroDesc: "Your AI Agent answers every call and message instantly, 24/7. It sounds completely natural, answers questions about your services, qualifies leads, and books appointments — all while you focus on the job.",
    desc: "Our AI Agent answers every call and chat instantly, 24/7. It sounds natural, answers questions, qualifies leads, and books appointments — all while you focus on the job.",
    stats: [
      { value: "85%", label: "of callers won't leave voicemail" },
      { value: "24/7", label: "availability without hiring" },
      { value: "$0", label: "extra staff cost" },
    ],
    features: [
      "Natural-Sounding AI Voice",
      "Instant Lead Qualification",
      "Appointment Booking",
      "FAQ Auto-Responses",
      "Call Recording & Transcripts",
      "Seamless CRM Integration",
    ],
    benefits: [
      { title: "Zero Missed Calls", desc: "Every call is answered within 2 rings, 24/7/365 — even on holidays, weekends, and when you're on a job site." },
      { title: "Sounds Like a Real Person", desc: "Our AI voice is indistinguishable from a human receptionist — customers get a professional experience every time." },
      { title: "Instant Appointment Booking", desc: "The AI checks your calendar and books estimates automatically — no back-and-forth, no phone tag." },
      { title: "Full Call Intelligence", desc: "Every call is recorded, transcribed, and summarized — so you always know what was discussed and what was promised." },
    ],
    howItWorks: [
      { step: "01", title: "Customer Calls or Messages", desc: "A prospect calls your number or sends a message on any channel — the AI answers instantly." },
      { step: "02", title: "AI Qualifies & Books", desc: "The AI asks the right questions, answers their questions, and books an estimate directly on your calendar." },
      { step: "03", title: "You Get the Summary", desc: "You receive a notification with the call summary, lead details, and booked appointment — ready to close." },
    ],
    image: AI_DASHBOARD,
    imageAlt: "AI marketing dashboard with lead pipeline",
  },
  {
    id: "smart-website",
    number: "04",
    icon: Globe,
    label: "A Website That Works As Hard As You Do",
    title: "Smart Website",
    tagline: "Professional, converting, and completely maintenance-free.",
    quote: '"You know you need a professional website, but who has time to manage it? Between estimates, jobs, and running a business, web design is the last thing on your mind."',
    heroDesc: "We build, maintain, and continuously optimize your website — you never touch it. It's always updated, always secure, always ranking in local search, and always converting visitors into paying customers.",
    desc: "We build, maintain, and continuously optimize your website — you never touch it. It's always updated, always secure, and always converting visitors into leads.",
    stats: [
      { value: "75%", label: "judge credibility by website" },
      { value: "0.05s", label: "to make first impression" },
      { value: "0hrs", label: "maintenance on your end" },
    ],
    features: [
      "Custom Professional Design",
      "Regular Content Updates",
      "Security & Maintenance",
      "Smart Chat Widget",
      "Universal Inbox",
      "Local SEO Optimized",
    ],
    benefits: [
      { title: "Built to Convert, Not Just Look Good", desc: "Every page is designed with one goal: turning visitors into booked jobs. Strategic CTAs, trust signals, and social proof throughout." },
      { title: "Completely Done-For-You", desc: "We handle design, development, hosting, security, updates, and content. You never log into a dashboard unless you want to." },
      { title: "Local SEO Built In", desc: "Your site is structured to rank for local searches like 'HVAC contractor near me' — bringing in organic leads every month." },
      { title: "Smart Chat That Captures Leads", desc: "An AI-powered chat widget on your site captures after-hours visitors and converts them into booked appointments automatically." },
    ],
    howItWorks: [
      { step: "01", title: "We Build Your Site", desc: "Our team designs and builds a custom, professional website tailored to your trade and service area." },
      { step: "02", title: "We Keep It Updated", desc: "We add new project photos, update content, and continuously optimize for local search — hands-free for you." },
      { step: "03", title: "Leads Come to You", desc: "Your site ranks in local search, impresses visitors, and converts them into booked estimates automatically." },
    ],
    image: CONTRACTOR_WORK,
    imageAlt: "Professional contractor team",
  },
  {
    id: "reactivator",
    number: "05",
    icon: RefreshCw,
    label: "Your Past Customers Are Gold",
    title: "Re-Activator",
    tagline: "Turn your existing customer base into a revenue engine.",
    quote: '"You\'ve served hundreds of customers over the years, but you only hear from them when something breaks. Meanwhile, they\'re hiring other contractors for jobs you could have had."',
    heroDesc: "Re-Activator automatically stays in touch with every past customer — seasonal reminders, birthday messages, special offers, and referral requests — so when they need a contractor again, you're the first call they make.",
    desc: "Re-Activator automatically stays in touch with your past customers — birthday wishes, seasonal reminders, special offers. When they need a contractor, your name is first.",
    stats: [
      { value: "5X", label: "cheaper than new customers" },
      { value: "67%", label: "more likely to buy again" },
      { value: "∞", label: "lifetime value potential" },
    ],
    features: [
      "Automated Holiday Campaigns",
      "Win-Back Targeted Offers",
      "Birthday & Anniversary Touches",
      "Seasonal Service Reminders",
      "Referral Program Automation",
      "Feedback & Review Requests",
    ],
    benefits: [
      { title: "Automated Seasonal Campaigns", desc: "Pre-built campaigns for spring tune-ups, winter prep, and holiday specials go out automatically to your entire customer list." },
      { title: "Win-Back Sequences", desc: "Customers who haven't booked in 6+ months get a targeted offer designed to bring them back — without you lifting a finger." },
      { title: "Referral Program on Autopilot", desc: "Happy customers are automatically asked for referrals at the perfect moment — turning your best customers into your best salespeople." },
      { title: "Review Generation", desc: "After every completed job, customers receive a perfectly-timed review request — building your Google rating consistently over time." },
    ],
    howItWorks: [
      { step: "01", title: "We Import Your Customers", desc: "We upload your existing customer list into the system — even if it's just a spreadsheet or old invoices." },
      { step: "02", title: "Campaigns Run Automatically", desc: "Seasonal messages, win-back offers, and referral requests go out at the perfect time — no manual work required." },
      { step: "03", title: "Old Customers Book New Jobs", desc: "Past customers re-engage, book new services, and refer their friends — turning your history into recurring revenue." },
    ],
    image: LEAD_CLOSER,
    imageAlt: "Contractor managing customer relationships",
  },
  {
    id: "google-optimizer",
    number: "06",
    icon: Star,
    label: "Own Your Local Search Results",
    title: "Google Optimizer",
    tagline: "Dominate local search and become the obvious choice.",
    quote: '"Your Google listing has 4 reviews from 2019. Your competitor has 87 reviews and shows up first for every search. You\'re invisible to customers actively looking for you."',
    heroDesc: "We fully optimize your Google Business Profile, generate a consistent stream of 5-star reviews, respond to every review with AI, and post regular updates — so your listing climbs the rankings and becomes a lead machine.",
    desc: "We optimize your Google Business Profile, generate consistent reviews, and respond to every one with AI. Your listing climbs the rankings and becomes a lead machine.",
    stats: [
      { value: "46%", label: "of Google searches are local" },
      { value: "88%", label: "trust online reviews" },
      { value: "#1", label: "position gets 33% of clicks" },
    ],
    features: [
      "Complete Profile Optimization",
      "Automated Review Generation",
      "AI-Powered Review Replies",
      "4 Google Posts/Month",
      "Reputation Monitoring",
      "Competitor Analysis",
    ],
    benefits: [
      { title: "Complete Profile Overhaul", desc: "We optimize every element of your Google Business Profile — photos, categories, services, hours, and description — for maximum visibility." },
      { title: "Consistent Review Generation", desc: "After every job, customers receive a frictionless review request. We make it so easy they actually do it — building your rating fast." },
      { title: "AI Review Responses", desc: "Every review — positive or negative — gets a professional, personalized AI response within hours, showing Google and customers you're engaged." },
      { title: "Regular Google Posts", desc: "We publish 4 keyword-rich posts per month to your listing, signaling activity to Google and giving customers fresh reasons to call." },
    ],
    howItWorks: [
      { step: "01", title: "We Audit & Optimize", desc: "We do a full audit of your current Google listing and fix everything — photos, categories, services, and business info." },
      { step: "02", title: "Reviews Start Flowing In", desc: "Automated review requests go out after every job. AI responds to every review within hours." },
      { step: "03", title: "Your Ranking Climbs", desc: "More reviews, regular posts, and full optimization push you up the local search rankings — bringing in more organic leads." },
    ],
    image: GOOGLE_REVIEWS,
    imageAlt: "Google Business Profile with 5-star reviews",
  },
];

export const allSolutionsNav = solutionsData.map((s) => ({
  id: s.id,
  title: s.title,
  label: s.label,
  icon: s.icon,
  href: `/solutions/${s.id}`,
}));
