import { Zap, Camera, Bot, Globe, RefreshCw, Star } from "lucide-react";
import type { SolutionData } from "@/components/SolutionPage";

const AI_DASHBOARD = "https://d2xsxph8kpxj0f.cloudfront.net/310519663485111386/DggHMYqYmKSoMpB2pB5sTZ/ai-dashboard-ZQvQg4K9jvT4urMpz8tHsh.webp";
const LEAD_CLOSER = "https://d2xsxph8kpxj0f.cloudfront.net/310519663485111386/DggHMYqYmKSoMpB2pB5sTZ/lead-closer-2mGVu2toi2ThpCWjbnyWaU.webp";
const CONTRACTOR_WORK = "https://d2xsxph8kpxj0f.cloudfront.net/310519663485111386/DggHMYqYmKSoMpB2pB5sTZ/contractor-work-n3H8tibW5po8kuFCJYpTqK.webp";
const GOOGLE_REVIEWS = "https://d2xsxph8kpxj0f.cloudfront.net/310519663485111386/DggHMYqYmKSoMpB2pB5sTZ/google-reviews-NjJWK5X2ixFWSDXEKDaQGJ.webp";

export const solutionsData: SolutionData[] = [
  {
    id: "lead-closer",
    number: "01",
    icon: Zap,
    label: "Tu Máquina de Ventas 24/7",
    title: "Lead Closer",
    tagline: "Nunca pierdas un lead a la competencia otra vez.",
    quote: '"Estás en un job site, cubierto de polvo de drywall, y tu teléfono suena con 3 nuevas solicitudes de cotización. Para cuando llegas a casa, esos leads ya llamaron a tu competencia."',
    heroDesc: "Lead Closer es tu máquina de ventas siempre activa — responde cada consulta en minutos, califica leads automáticamente, y los mantiene calientes hasta que estés listo para cerrar. Tu pipeline se mantiene lleno mientras tú te concentras en el trabajo.",
    desc: "Lead Closer responde al instante, califica leads, y los mantiene calientes hasta que estés listo para cerrar. Tu pipeline se mantiene lleno mientras haces el trabajo que amas.",
    stats: [
      { value: "78%", label: "de los leads van al primer que responde" },
      { value: "5 min", label: "tiempo óptimo de respuesta" },
      { value: "3X", label: "más conversiones" },
    ],
    features: [
      "Smart Pipeline Dashboard",
      "Formularios de Captura Personalizados",
      "SMS Bidireccional y Seguimiento de Llamadas",
      "Campañas Drip Automatizadas",
      "Workflows de Configura-y-Olvida",
      "Alcance por Email y SMS",
    ],
    benefits: [
      { title: "Respuesta Instantánea a Leads", desc: "Cada nueva consulta recibe una respuesta automatizada y personalizada en minutos — incluso a las 2am un domingo." },
      { title: "Calificación Inteligente de Leads", desc: "El AI filtra a los que solo están viendo y resalta tus prospectos más calientes para que solo inviertas tiempo en leads listos para comprar." },
      { title: "Secuencias de Seguimiento Automatizadas", desc: "Campañas drip multi-contacto mantienen los leads calientes por días y semanas hasta que estén listos para agendar — sin esfuerzo manual." },
      { title: "Visibilidad Completa del Pipeline", desc: "Ve cada lead, en qué parte del funnel están, y qué acción tomar después — todo en un dashboard limpio." },
    ],
    howItWorks: [
      { step: "01", title: "Llega un Lead", desc: "Un prospecto llena tu formulario, llama, o te manda mensaje por cualquier canal — web, social, o Google." },
      { step: "02", title: "El AI Responde al Instante", desc: "Lead Closer manda una respuesta personalizada en minutos, califica el lead, y agenda una llamada o estimado." },
      { step: "03", title: "Cierras el Trato", desc: "Recibes notificación de un lead caliente y pre-calificado. Llegas, cierras el job, y cobras." },
    ],
    image: LEAD_CLOSER,
    imageAlt: "Contratista revisando leads en el teléfono en un job site",
  },
  {
    id: "job-promoter",
    number: "02",
    icon: Camera,
    label: "Tu Trabajo Habla — Nosotros Lo Hacemos Sonar",
    title: "Job Promoter",
    tagline: "Tu craftsmanship finalmente recibe la atención que merece.",
    quote: '"Tu Instagram está vacío. Tu website muestra trabajos de hace 3 años. Mientras tanto, un competidor con la mitad de tu skill está cerrando jobs porque se ve más profesional online."',
    heroDesc: "Job Promoter convierte tus proyectos terminados en una máquina poderosa de marketing — fotos profesionales, videos cinematográficos, y showcases de antes y después distribuidos en todas las plataformas que importan para tus clientes.",
    desc: "Capturamos tu mejor trabajo con lookbooks profesionales, videos, y antes/después — luego los distribuimos en todas las plataformas que importan.",
    stats: [
      { value: "93%", label: "revisan opiniones antes de contratar" },
      { value: "4X", label: "más engagement con video" },
      { value: "87%", label: "confían más en visuales que en texto" },
    ],
    features: [
      "Lookbooks de Calidad Revista",
      "Galería de Fotos Organizada",
      "Estudios de Caso Detallados",
      "Optimización SEO y AI",
      "Hasta 25 Videos al Mes",
      "Publicaciones Sociales Consistentes",
    ],
    benefits: [
      { title: "Contenido Visual Profesional", desc: "Transformamos tus fotos de job site en visuales pulidos, de calidad revista, que hacen que los clientes confíen en ti antes de llamar." },
      { title: "Videos Que Convierten", desc: "Videos cortos de tu trabajo generan 4x más engagement que fotos — producimos hasta 25 al mes, totalmente branded." },
      { title: "Publicación Social Automatizada", desc: "Tu mejor trabajo se publica consistentemente en Instagram, Facebook, y Google — sin que muevas un dedo." },
      { title: "Showcases Optimizados para SEO", desc: "Cada página de proyecto está optimizada para rankear en búsquedas locales, trayendo leads orgánicos de gente buscando tus servicios exactos." },
    ],
    howItWorks: [
      { step: "01", title: "Nos Mandas Tus Fotos", desc: "Después de cada job, toma fotos con tu teléfono y mándalas. Ese es tu único trabajo." },
      { step: "02", title: "Creamos el Contenido", desc: "Nuestro equipo transforma tus fotos crudas en lookbooks profesionales, videos, y posts sociales — totalmente branded." },
      { step: "03", title: "Distribuimos en Todas Partes", desc: "El contenido se publica en tu website, redes sociales, y Google — construyendo tu reputación en piloto automático." },
    ],
    image: CONTRACTOR_WORK,
    imageAlt: "Contratistas profesionales trabajando en proyecto residencial",
  },
  {
    id: "ai-agent",
    number: "03",
    icon: Bot,
    label: "Nunca Pierdas Otra Llamada",
    title: "AI Agent",
    tagline: "Cada llamada contestada. Cada lead capturado. 24/7.",
    quote: '"No puedes contestar cada llamada cuando estás a 20 pies en una escalera o hasta la rodilla en una remodelación. Pero cada llamada perdida es dinero que se va."',
    heroDesc: "Tu AI Agent contesta cada llamada y mensaje al instante, 24/7. Suena completamente natural, responde preguntas sobre tus servicios, califica leads, y agenda citas — mientras tú te concentras en el trabajo.",
    desc: "Nuestro AI Agent contesta cada llamada y chat al instante, 24/7. Suena natural, responde preguntas, califica leads, y agenda citas — mientras tú haces el trabajo.",
    stats: [
      { value: "85%", label: "de los que llaman no dejan buzón" },
      { value: "24/7", label: "disponibilidad sin contratar" },
      { value: "$0", label: "costo extra de staff" },
    ],
    features: [
      "Voz AI que Suena Natural",
      "Calificación Instantánea de Leads",
      "Agendamiento de Citas",
      "Respuestas Automáticas a FAQs",
      "Grabación y Transcripción de Llamadas",
      "Integración Fluida con CRM",
    ],
    benefits: [
      { title: "Cero Llamadas Perdidas", desc: "Cada llamada se contesta en 2 timbres, 24/7/365 — incluso festivos, fines de semana, y cuando estás en un job site." },
      { title: "Suena Como Persona Real", desc: "Nuestra voz AI es indistinguible de una recepcionista humana — los clientes tienen una experiencia profesional siempre." },
      { title: "Agendamiento Instantáneo", desc: "El AI revisa tu calendario y agenda estimados automáticamente — sin ida y vuelta ni juego de teléfono." },
      { title: "Inteligencia Completa de Llamadas", desc: "Cada llamada se graba, transcribe, y resume — para que siempre sepas qué se habló y qué se prometió." },
    ],
    howItWorks: [
      { step: "01", title: "Cliente Llama o Manda Mensaje", desc: "Un prospecto llama a tu número o manda mensaje por cualquier canal — el AI contesta al instante." },
      { step: "02", title: "AI Califica y Agenda", desc: "El AI hace las preguntas correctas, responde dudas, y agenda un estimado directo en tu calendario." },
      { step: "03", title: "Recibes el Resumen", desc: "Recibes notificación con resumen de la llamada, detalles del lead, y cita agendada — listo para cerrar." },
    ],
    image: AI_DASHBOARD,
    imageAlt: "Dashboard de marketing AI con pipeline de leads",
  },
  {
    id: "smart-website",
    number: "04",
    icon: Globe,
    label: "Un Website Que Trabaja Tan Duro Como Tú",
    title: "Smart Website",
    tagline: "Profesional, que convierte, y sin mantenimiento para ti.",
    quote: '"Sabes que necesitas un website profesional, pero ¿quién tiene tiempo para manejarlo? Entre estimados, jobs, y manejar el negocio, el diseño web es lo último en tu mente."',
    heroDesc: "Construimos, mantenemos, y optimizamos continuamente tu website — tú nunca lo tocas. Siempre actualizado, seguro, rankeando en búsqueda local, y convirtiendo visitantes en clientes que pagan.",
    desc: "Construimos, mantenemos, y optimizamos continuamente tu website — tú nunca lo tocas. Siempre actualizado, seguro, y convirtiendo visitantes en leads.",
    stats: [
      { value: "75%", label: "juzgan credibilidad por el website" },
      { value: "0.05s", label: "para causar primera impresión" },
      { value: "0hrs", label: "mantenimiento de tu parte" },
    ],
    features: [
      "Diseño Profesional Personalizado",
      "Actualizaciones Regulares de Contenido",
      "Seguridad y Mantenimiento",
      "Widget de Chat Inteligente",
      "Inbox Universal",
      "Optimizado para SEO Local",
    ],
    benefits: [
      { title: "Diseñado para Convertir, No Solo Verse Bien", desc: "Cada página tiene un objetivo: convertir visitantes en jobs agendados. CTAs estratégicos, señales de confianza, y prueba social por todo lado." },
      { title: "Completamente Hecho Para Ti", desc: "Nosotros manejamos diseño, desarrollo, hosting, seguridad, actualizaciones, y contenido. Tú solo entras si quieres." },
      { title: "SEO Local Integrado", desc: "Tu sitio está estructurado para rankear en búsquedas locales como 'HVAC contractor near me' — trayendo leads orgánicos cada mes." },
      { title: "Chat Inteligente Que Captura Leads", desc: "Un widget de chat con AI en tu sitio captura visitantes fuera de horario y los convierte en citas agendadas automáticamente." },
    ],
    howItWorks: [
      { step: "01", title: "Construimos Tu Sitio", desc: "Nuestro equipo diseña y construye un website profesional y personalizado para tu trade y área de servicio." },
      { step: "02", title: "Lo Mantenemos Actualizado", desc: "Agregamos fotos nuevas de proyectos, actualizamos contenido, y optimizamos para búsqueda local — sin que muevas un dedo." },
      { step: "03", title: "Los Leads Llegan a Ti", desc: "Tu sitio rankea en búsqueda local, impresiona visitantes, y los convierte en estimados agendados automáticamente." },
    ],
    image: CONTRACTOR_WORK,
    imageAlt: "Equipo profesional de contratistas",
  },
  {
    id: "reactivator",
    number: "05",
    icon: RefreshCw,
    label: "Tus Clientes Pasados Son Oro",
    title: "Re-Activator",
    tagline: "Convierte tu base de clientes existente en una máquina de ingresos.",
    quote: '"Has servido a cientos de clientes en los años, pero solo sabes de ellos cuando algo se rompe. Mientras tanto, están contratando otros contractors para jobs que podrían ser tuyos."',
    heroDesc: "Re-Activator se mantiene en contacto automáticamente con cada cliente pasado — recordatorios estacionales, mensajes de cumpleaños, ofertas especiales, y solicitudes de referidos — para que cuando necesiten un contractor, tú seas la primera llamada.",
    desc: "Re-Activator se mantiene en contacto automático con tus clientes pasados — felicitaciones de cumpleaños, recordatorios estacionales, ofertas especiales. Cuando necesitan contractor, tu nombre es el primero.",
    stats: [
      { value: "5X", label: "más barato que conseguir clientes nuevos" },
      { value: "67%", label: "más probabilidad de comprar otra vez" },
      { value: "∞", label: "potencial de valor de por vida" },
    ],
    features: [
      "Campañas Automáticas de Fiestas",
      "Ofertas Dirigidas para Recuperar Clientes",
      "Toques de Cumpleaños y Aniversarios",
      "Recordatorios de Servicio Estacionales",
      "Automatización de Programa de Referidos",
      "Solicitudes de Feedback y Reviews",
    ],
    benefits: [
      { title: "Campañas Estacionales Automatizadas", desc: "Campañas pre-hechas para tune-ups de primavera, preparación para invierno, y especiales de fiestas se envían automáticamente a toda tu lista." },
      { title: "Secuencias para Recuperar Clientes", desc: "Clientes que no han reservado en 6+ meses reciben ofertas dirigidas para traerlos de vuelta — sin que muevas un dedo." },
      { title: "Programa de Referidos en Piloto Automático", desc: "Clientes felices reciben solicitudes de referidos en el momento perfecto — convirtiendo tus mejores clientes en tus mejores vendedores." },
      { title: "Generación de Reviews", desc: "Después de cada job completado, los clientes reciben una solicitud de review en el momento justo — construyendo tu rating en Google consistentemente." },
    ],
    howItWorks: [
      { step: "01", title: "Importamos Tus Clientes", desc: "Subimos tu lista actual de clientes al sistema — aunque sea solo una hoja de cálculo o facturas viejas." },
      { step: "02", title: "Las Campañas Corren Solas", desc: "Mensajes estacionales, ofertas para recuperar clientes, y solicitudes de referidos se envían en el momento perfecto — sin trabajo manual." },
      { step: "03", title: "Clientes Viejos Reservan Nuevos Jobs", desc: "Clientes pasados se reactivan, reservan nuevos servicios, y refieren a sus amigos — convirtiendo tu historia en ingresos recurrentes." },
    ],
    image: LEAD_CLOSER,
    imageAlt: "Contratista manejando relaciones con clientes",
  },
  {
    id: "google-optimizer",
    number: "06",
    icon: Star,
    label: "Domina Tus Resultados Locales",
    title: "Google Optimizer",
    tagline: "Domina la búsqueda local y conviértete en la opción obvia.",
    quote: '"Tu ficha de Google tiene 4 reviews de 2019. Tu competencia tiene 87 reviews y aparece primero en todas las búsquedas. Eres invisible para clientes que te están buscando activamente."',
    heroDesc: "Optimizamos completamente tu Google Business Profile, generamos un flujo constante de reviews 5 estrellas, respondemos cada review con AI, y publicamos actualizaciones regulares — para que tu ficha suba en el ranking y se convierta en una máquina de leads.",
    desc: "Optimizamos tu Google Business Profile, generamos reviews consistentes, y respondemos cada una con AI. Tu ficha sube en el ranking y se vuelve una máquina de leads.",
    stats: [
      { value: "46%", label: "de las búsquedas en Google son locales" },
      { value: "88%", label: "confían en reviews online" },
      { value: "#1", label: "posición recibe 33% de los clics" },
    ],
    features: [
      "Optimización Completa del Perfil",
      "Generación Automática de Reviews",
      "Respuestas a Reviews con AI",
      "4 Posts en Google al Mes",
      "Monitoreo de Reputación",
      "Análisis de Competencia",
    ],
    benefits: [
      { title: "Revisión Completa del Perfil", desc: "Optimizamos cada elemento de tu Google Business Profile — fotos, categorías, servicios, horarios, y descripción — para máxima visibilidad." },
      { title: "Generación Consistente de Reviews", desc: "Después de cada job, los clientes reciben una solicitud de review sin fricción. Lo hacemos tan fácil que realmente la hacen — subiendo tu rating rápido." },
      { title: "Respuestas AI a Reviews", desc: "Cada review — positiva o negativa — recibe una respuesta profesional y personalizada con AI en horas, mostrando a Google y clientes que estás activo." },
      { title: "Posts Regulares en Google", desc: "Publicamos 4 posts al mes con keywords en tu ficha, señalando actividad a Google y dando a clientes razones frescas para llamar." },
    ],
    howItWorks: [
      { step: "01", title: "Auditamos y Optimizamos", desc: "Hacemos una auditoría completa de tu ficha actual de Google y arreglamos todo — fotos, categorías, servicios, y datos del negocio." },
      { step: "02", title: "Empiezan a Llegar Reviews", desc: "Solicitudes automáticas de reviews se envían después de cada job. AI responde cada review en horas." },
      { step: "03", title: "Tu Ranking Sube", desc: "Más reviews, posts regulares, y optimización completa te suben en el ranking local — trayendo más leads orgánicos." },
    ],
    image: GOOGLE_REVIEWS,
    imageAlt: "Ficha de Google Business con reviews de 5 estrellas",
  },
];

export const allSolutionsNav = solutionsData.map((s) => ({
  id: s.id,
  title: s.title,
  label: s.label,
  icon: s.icon,
  href: `/solutions/${s.id}`,
}));